; PlatformIO Project Configuration File
; Sunton ESP32-8048S070 (7" 800x480 RGB TFT with GT911 Touch)

[env:esp32-8048S070]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

; Flash and PSRAM configuration (ESP32-S3-WROOM-1-N16R8)
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_build.partitions = partitions.csv

build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=0
    -DLV_CONF_INCLUDE_SIMPLE
    -DLV_LVGL_H_INCLUDE_SIMPLE
    -DDEBUG=1
    -I include

lib_deps =
    lvgl/lvgl@~8.4.0
    moononournation/GFX Library for Arduino@^1.4.0
    https://github.com/trailcurrentoss/ESP32ArduinoDebugLibrary.git
    https://github.com/trailcurrentoss/TwaiTaskBasedLibraryWROOM32.git
    https://github.com/trailcurrentoss/OtaUpdateLibraryWROOM32.git

monitor_speed = 115200
