// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: sq_ui

#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

#include "ui.h"
#include "ui_helpers.h"

#include "rs485.h"
#include "can.h"
#include "pwm.h"
#include "wifi.h"

///////////////////// VARIABLES ////////////////////

// SCREEN: ui_Login
void ui_Login_screen_init(void);
lv_obj_t * ui_Login;
lv_obj_t * ui_Login_Panel1;
lv_obj_t * ui_Login_Keyboard;
lv_obj_t * ui_Login_Panel2;
void ui_event_Login_Label0(lv_event_t * e);
lv_obj_t * ui_Login_Label0;
lv_obj_t * ui_Login_Label1;
lv_obj_t * ui_Login_Label2;
void ui_event_Login_InputUser(lv_event_t * e);
lv_obj_t * ui_Login_InputUser;
void ui_event_Login_InputPass(lv_event_t * e);
lv_obj_t * ui_Login_InputPass;
void ui_event_Login_InputPass_EYE(lv_event_t * e);
lv_obj_t * ui_Login_InputPass_EYE;
lv_obj_t * ui_Login_Panel3;
lv_obj_t * ui_Login_Label3;

// CUSTOM VARIABLES for Login Screen
bool WIFI_INPUT_PWD_FLAG = true;  // Flag to check if password input is visible

char saved_username[MAX_LENGTH] = "";  // Store the saved username
char saved_password[MAX_LENGTH] = "";  // Store the saved password
char entered_username[MAX_LENGTH] = "";  // Store the entered username
char entered_password[MAX_LENGTH] = "";  // Store the entered password

// SCREEN: ui_Create_User
void ui_Create_Uesr_screen_init(void);
lv_obj_t * ui_Create_Uesr;
lv_obj_t * ui_Create_Uesr_Panel0;
lv_obj_t * ui_Create_Uesr_Label0;
lv_obj_t * ui_Create_Uesr_Label1;
void ui_event_Create_Uesr_Name(lv_event_t * e);
lv_obj_t * ui_Create_Uesr_Name;
void ui_event_Create_Uesr_Password(lv_event_t * e);
lv_obj_t * ui_Create_Uesr_Password;
void ui_event_Create_Uesr_Pwd_EYE(lv_event_t * e);
lv_obj_t * ui_Create_Uesr_Pwd_EYE;
lv_obj_t * ui_Create_Uesr_Keyboard0;
void ui_event_Create_Uesr_Button0(lv_event_t * e);
lv_obj_t * ui_Create_Uesr_Button0;
lv_obj_t * ui_Create_Uesr_Label2;
lv_obj_t * ui_Create_Uesr_Label3;

// CUSTOM VARIABLES for Create User Screen
bool WIFI_Create_PWD_FLAG = true;  // Flag to check if password creation is visible

// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t * ui_Main;
void ui_event_Wifi(lv_event_t * e);
lv_obj_t * ui_Wifi;
lv_obj_t * ui_Wifi_Label0;
void ui_event_RS485(lv_event_t * e);
lv_obj_t * ui_RS485;
lv_obj_t * ui_RS485_Label0;
void ui_event_CAN(lv_event_t * e);
lv_obj_t * ui_CAN;
lv_obj_t * ui_CAN_Label0;
void ui_event_PWM(lv_event_t * e);
lv_obj_t * ui_PWM;
lv_obj_t * ui_PWM_Label10;

// CUSTOM VARIABLES for Main Screen

// SCREEN: ui_Main_RS485
void ui_Main_RS485_screen_init(void);
lv_obj_t * ui_Main_RS485;
void ui_event_RS485_Button1(lv_event_t * e);
lv_obj_t * ui_RS485_Button1;
lv_obj_t * ui_RS485_Label1;
lv_obj_t * ui_RS485_Keyboard1;
lv_obj_t * ui_RS485_Send;
lv_obj_t * ui_RS485_Send_Box;
void ui_event_RS485_Send_Area(lv_event_t * e);
lv_obj_t * ui_RS485_Send_Area;
void ui_event_RS485_Button3(lv_event_t * e);
lv_obj_t * ui_RS485_Button3;
lv_obj_t * ui_RS485_Label3;
void ui_event_RS485_Button4(lv_event_t * e);
lv_obj_t * ui_RS485_Button4;
lv_obj_t * ui_RS485_Label4;
lv_obj_t * ui_RS485_Read;
lv_obj_t * ui_RS485_Read_Area;
lv_obj_t * ui_RS485_Read_Box;
void ui_event_RS485_Button2(lv_event_t * e);
lv_obj_t * ui_RS485_Button2;
lv_obj_t * ui_RS485_Label2;
lv_obj_t * ui_RS485_Roller1;
// CUSTOM VARIABLES
bool RS485_Clear = false;  // Flag for RS485 clear action
uint32_t RS485_BaudRate = ECHO_TEST_BAUDRATE;  // Baud rate for RS485 communication

// SCREEN: ui_Main_CAN
void ui_Main_CAN_screen_init(void);
lv_obj_t * ui_Main_CAN;
void ui_event_CAN_Button1(lv_event_t * e);
lv_obj_t * ui_CAN_Button1;
lv_obj_t * ui_CAN_Label1;
lv_obj_t * ui_CAN_Keyboard0;
lv_obj_t * ui_CAN_Send1;
lv_obj_t * ui_CAN_Send_Box;
void ui_event_CAN_Send_ID(lv_event_t * e);
lv_obj_t * ui_CAN_Send_ID;
void ui_event_CAN_Send_Len(lv_event_t * e);
lv_obj_t * ui_CAN_Send_Len;
void ui_event_CAN_Send_Data(lv_event_t * e);
lv_obj_t * ui_CAN_Send_Data;
void ui_event_CAN_Button2(lv_event_t * e);
lv_obj_t * ui_CAN_Button2;
lv_obj_t * ui_CAN_Label2;
void ui_event_CAN_Button3(lv_event_t * e);
lv_obj_t * ui_CAN_Button3;
lv_obj_t * ui_CAN_Label3;
lv_obj_t * ui_CAN_Read1;
lv_obj_t * ui_CAN_Read_Area;
lv_obj_t * ui_CAN_Read_Box;
void ui_event_CAN_Button4(lv_event_t * e);
lv_obj_t * ui_CAN_Button4;
lv_obj_t * ui_CAN_Label4;
lv_obj_t * ui_CAN_Roller;
// CUSTOM VARIABLES
bool CAN_Clear = false;  // Flag for CAN clear action

// SCREEN: ui_Main_PWM
void ui_Main_PWM_screen_init(void);
lv_obj_t * ui_Main_PWM;
lv_obj_t * ui_PWM_Panel1;
void ui_event_PWM_Arc0(lv_event_t * e);
lv_obj_t * ui_PWM_Arc0;
lv_obj_t * ui_PWM_Label0;
lv_obj_t * ui_PWM_Label9;
lv_obj_t * ui_BAT_Label0;
lv_obj_t * ui_PWM_Panel2;
void ui_event_PWM_Slider0(lv_event_t * e);
lv_obj_t * ui_PWM_Slider0;
lv_obj_t * ui_PWM_Label1;
lv_obj_t * ui_PWM_Panel3;
void ui_event_PWM_Switch1(lv_event_t * e);
lv_obj_t * ui_PWM_Switch1;
void ui_event_PWM_Switch2(lv_event_t * e);
lv_obj_t * ui_PWM_Switch2;
void ui_event_PWM_Switch3(lv_event_t * e);
lv_obj_t * ui_PWM_Switch3;
lv_obj_t * ui_PWM_Label2;
lv_obj_t * ui_PWM_Label3;
lv_obj_t * ui_PWM_Label4;
lv_obj_t * ui_PWM_Panel4;
lv_obj_t * ui_PWM_Label5;
lv_obj_t * ui_PWM_Label6;
lv_obj_t * ui_PWM_Label7;
void ui_event_PWM_Button0(lv_event_t * e);
lv_obj_t * ui_PWM_Button0;
lv_obj_t * ui_PWM_Label8;
// CUSTOM VARIABLES

// SCREEN: ui_Main_WIFI
void ui_Main_WIFI_screen_init(void);
lv_obj_t * ui_Main_WIFI;
lv_obj_t * ui_WIFI;

lv_obj_t * ui_WIFI_STA;
lv_obj_t * ui_WIFI_SCAN_STA;
void ui_event_WIFI_Button0(lv_event_t * e);
lv_obj_t * ui_WIFI_Button0;
lv_obj_t * ui_WIFI_Label0;
void ui_event_WIFI_OPEN(lv_event_t * e);
lv_obj_t * ui_WIFI_OPEN;
lv_obj_t * ui_WIFI_STA_Label;
lv_obj_t * ui_WIFI_List_Win;
lv_obj_t * ui_WIFI_Spinner;
lv_obj_t * ui_WIFI_Details_Win;
lv_obj_t * ui_WIFI_Name;
lv_obj_t * ui_WIFI_Aurhmode;
lv_obj_t * ui_WIFI_Pairwise;
lv_obj_t * ui_WIFI_Group;
lv_obj_t * ui_WIFI_Channel;
lv_obj_t * ui_WIFI_IP;
void ui_event_WIFI_Connection_BUTTON(lv_event_t * e);
lv_obj_t * ui_WIFI_Connection_BUTTON;
lv_obj_t * ui_Connection;
void ui_event_WIFI_INPUT_PWD(lv_event_t * e);
lv_obj_t * ui_WIFI_INPUT_PWD;
void ui_event_WIFI_EYE(lv_event_t * e);
lv_obj_t * ui_WIFI_EYE;
lv_obj_t * ui_WIFI_INPUT_KEYBOARD;
lv_obj_t * ui_WIFI_Wait_CONNECTION;
lv_obj_t * ui_WIFI_PWD_Error;

lv_obj_t * ui_WIFI_AP;
lv_obj_t * ui_WIFI_OPEN_AP_;
void ui_event_WIFI_Button2(lv_event_t * e);
lv_obj_t * ui_WIFI_Button2;
lv_obj_t * ui_WIFI_Label2;
void ui_event_WIFI_AP_OPEN(lv_event_t * e);
lv_obj_t * ui_WIFI_AP_OPEN;
lv_obj_t * ui_WIFI_AP_INPUT_ERROR;
lv_obj_t * ui_WIFI_AP_Information;
void ui_event_WIFI_AP_NAME(lv_event_t * e);
lv_obj_t * ui_WIFI_AP_NAME;
void ui_event_WIFI_AP_Password(lv_event_t * e);
lv_obj_t * ui_WIFI_AP_Password;
void ui_event_WIFI_AP_EYE(lv_event_t * e);
lv_obj_t * ui_WIFI_AP_EYE;
void ui_event_WIFI_AP_Channel(lv_event_t * e);
lv_obj_t * ui_WIFI_AP_Channel;
lv_obj_t * ui_WIFI_AP_NAME_Label;
lv_obj_t * ui_WIFI_AP_PWD_Label;
lv_obj_t * ui_WIFI_AP_Channel_Label;
lv_obj_t * ui_WIFI_AP_MAC_ADDR;
lv_obj_t * ui_WIFI_AP_CON_NUM;
lv_obj_t * ui_WIFI_AP_Keyboard;
// CUSTOM VARIABLES
bool WIFI_SCAN_FLAG = false;
bool WIFI_STA_FLAG = false;
bool WIFI_AP_FLAG = false;
bool WIFI_DIS_PWD = true;
bool WIFI_AP_PWD = true;
int8_t WIFI_CONNECTION = -1;
int wifi_index = 0;
uint8_t *wifi_pwd;

lv_obj_t *ui_WIFI_SCAN_List;
lv_obj_t * WIFI_List_Button;

lv_obj_t *ui_WIFI_AP_MAC_List;

bool WIFI_CONNECTION_DONE = false;
void ui_WIFI_list_event_cb(lv_event_t * e);

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_[1] = {&ui_img_485_png};
const lv_img_dsc_t * ui_imgset_wifi_[4] = {&ui_img_wifi_1_png, &ui_img_wifi_2_png, &ui_img_wifi_3_png, &ui_img_wifi_4_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

// Event handler for the Login Label0 (when clicked, navigate to Create User screen)
void ui_event_Login_Label0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // Change screen to ui_Create_Uesr without animation and initialize it
        _ui_screen_change(&ui_Create_Uesr, LV_SCR_LOAD_ANIM_NONE, 0, 0, &ui_Create_Uesr_screen_init);
    }
}

// Event handler for the Login InputUser field (handling focus, defocus, and ready events)
void ui_event_Login_InputUser(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        // When focused, set the keyboard target to InputUser and show the keyboard
        _ui_keyboard_set_target(ui_Login_Keyboard,  ui_Login_InputUser);
        _ui_flag_modify(ui_Login_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        
        lv_textarea_set_placeholder_text(ui_Login_InputUser, ""); 
        lv_obj_set_style_bg_opa(ui_Login_InputUser, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        // When defocused, hide the keyboard and hide the additional UI elements
        _ui_flag_modify(ui_Login_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Login_Panel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        
        lv_textarea_set_placeholder_text(ui_Login_InputUser, "Enter username..."); 
        lv_obj_set_style_bg_opa(ui_Login_InputUser, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        
        lv_textarea_set_placeholder_text(ui_Login_InputPass, "Enter password..."); 
        lv_obj_set_style_bg_opa(ui_Login_InputPass, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);

    }
    if(event_code == LV_EVENT_READY) {
        // When the user is done entering data, handle the input and move focus to the next field
        // input_user_event_cb(e);
        _ui_keyboard_set_target(ui_Login_Keyboard,  ui_Login_InputPass);
        _ui_state_modify(ui_Login_InputUser, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Login_InputPass, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
        
        lv_textarea_set_placeholder_text(ui_Login_InputUser, "Enter username..."); 
        lv_obj_set_style_bg_opa(ui_Login_InputUser, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        
        lv_textarea_set_placeholder_text(ui_Login_InputPass, ""); 
        lv_obj_set_style_bg_opa(ui_Login_InputPass, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    }
}


// Event handler for the Login InputPass field (handling focus, defocus, and ready events)
void ui_event_Login_InputPass(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        // When focused, show the keyboard and set the target to InputPass
        _ui_flag_modify(ui_Login_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Login_Keyboard,  ui_Login_InputPass);
       
        lv_textarea_set_placeholder_text(ui_Login_InputPass, ""); 
        lv_obj_set_style_bg_opa(ui_Login_InputPass, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        // When defocused, hide the keyboard and additional UI elements
        _ui_flag_modify(ui_Login_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Login_Panel3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    
        lv_textarea_set_placeholder_text(ui_Login_InputUser, "Enter username..."); 
        lv_obj_set_style_bg_opa(ui_Login_InputUser, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        
        lv_textarea_set_placeholder_text(ui_Login_InputPass, "Enter password..."); 
        lv_obj_set_style_bg_opa(ui_Login_InputPass, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);

    }
    if(event_code == LV_EVENT_READY) {
        // When ready (password entered), handle the input and hide the keyboard
        input_user_event_cb(e);
        input_password_event_cb(e);
        _ui_state_modify(ui_Login_InputPass, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        _ui_flag_modify(ui_Login_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        
        lv_textarea_set_placeholder_text(ui_Login_InputPass, "Enter password..."); 
        lv_obj_set_style_bg_opa(ui_Login_InputPass, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
    }
}

// Event handler for the Login InputPass_EYE button (to toggle password visibility)
void ui_event_Login_InputPass_EYE(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // Toggle the password visibility flag and update the password mode
        WIFI_INPUT_PWD_FLAG = !WIFI_INPUT_PWD_FLAG;
        lv_textarea_set_password_mode(ui_Login_InputPass, WIFI_INPUT_PWD_FLAG);
        _ui_state_modify(ui_Login_InputPass, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
        _ui_keyboard_set_target(ui_Login_Keyboard,  ui_Login_InputPass);
        _ui_flag_modify(ui_Login_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// Event handler for the Create User Name input field (handling focus, defocus, and ready events)
void ui_event_Create_Uesr_Name(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        // When focused, show the keyboard and set the target to Name input field
        _ui_keyboard_set_target(ui_Create_Uesr_Keyboard0,  ui_Create_Uesr_Name);
        _ui_flag_modify(ui_Create_Uesr_Keyboard0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    
        lv_textarea_set_placeholder_text(ui_Create_Uesr_Name, ""); 
        lv_obj_set_style_bg_opa(ui_Create_Uesr_Name, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
        
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        // When defocused, hide the keyboard
        _ui_flag_modify(ui_Create_Uesr_Keyboard0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    
        lv_textarea_set_placeholder_text(ui_Create_Uesr_Name, "Enter username..."); 
        lv_obj_set_style_bg_opa(ui_Create_Uesr_Name, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        
        lv_textarea_set_placeholder_text(ui_Create_Uesr_Password, "Enter password..."); 
        lv_obj_set_style_bg_opa(ui_Create_Uesr_Password, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);

    }
    if(event_code == LV_EVENT_READY) {
        // When ready (name entered), handle the input and move to the next field
        
        _ui_keyboard_set_target(ui_Create_Uesr_Keyboard0,  ui_Create_Uesr_Password);
        _ui_state_modify(ui_Create_Uesr_Name, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Create_Uesr_Password, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
    
        lv_textarea_set_placeholder_text(ui_Create_Uesr_Name, "Enter username..."); 
        lv_obj_set_style_bg_opa(ui_Create_Uesr_Name, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        
        lv_textarea_set_placeholder_text(ui_Create_Uesr_Password, ""); 
        lv_obj_set_style_bg_opa(ui_Create_Uesr_Password, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);

    }
}

// Event handler for the Create User Password input field (handling focus, defocus, and ready events)
void ui_event_Create_Uesr_Password(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_FOCUSED) {
        // When focused, show the keyboard and set the target to Password input field
        _ui_flag_modify(ui_Create_Uesr_Keyboard0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Create_Uesr_Keyboard0,  ui_Create_Uesr_Password);
    
        lv_textarea_set_placeholder_text(ui_Create_Uesr_Password, ""); 
        lv_obj_set_style_bg_opa(ui_Create_Uesr_Password, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
        
    }
    if(event_code == LV_EVENT_DEFOCUSED) {
        // When defocused, hide the keyboard and additional UI elements
        _ui_flag_modify(ui_Create_Uesr_Keyboard0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Create_Uesr_Label2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    
        lv_textarea_set_placeholder_text(ui_Create_Uesr_Name, "Enter username..."); 
        lv_obj_set_style_bg_opa(ui_Create_Uesr_Name, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        
        lv_textarea_set_placeholder_text(ui_Create_Uesr_Password, "Enter password..."); 
        lv_obj_set_style_bg_opa(ui_Create_Uesr_Password, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);

    }
    if(event_code == LV_EVENT_READY) {
        // When ready (password entered), handle the password input
        new_user_event_cb(e);
        mew_password_event_cb(e);

        lv_textarea_set_placeholder_text(ui_Create_Uesr_Name, "Enter username..."); 
        lv_obj_set_style_bg_opa(ui_Create_Uesr_Name, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        
        lv_textarea_set_placeholder_text(ui_Create_Uesr_Password, "Enter password..."); 
        lv_obj_set_style_bg_opa(ui_Create_Uesr_Password, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);

    }
}

// Event handler for toggling the visibility of the password in the Create User password field
void ui_event_Create_Uesr_Pwd_EYE(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // Toggle the password visibility flag and update the password mode
        WIFI_Create_PWD_FLAG = !WIFI_Create_PWD_FLAG;
        lv_textarea_set_password_mode(ui_Create_Uesr_Password, WIFI_Create_PWD_FLAG);
        _ui_state_modify(ui_Create_Uesr_Password, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
        _ui_keyboard_set_target(ui_Create_Uesr_Keyboard0,  ui_Create_Uesr_Password);
        _ui_flag_modify(ui_Create_Uesr_Keyboard0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// Event handler for the Create User button (used to create the user and clear fields)
void ui_event_Create_Uesr_Button0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        // Disable fields and clear the text input fields
        _ui_state_modify(ui_Create_Uesr_Name, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_Create_Uesr_Password, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        lv_textarea_set_text(ui_Create_Uesr_Name, ""); // Clear the username field
        lv_textarea_set_text(ui_Create_Uesr_Password, ""); // Clear the password field
        
        // Hide the current button and label, then navigate to the Login screen
        _ui_flag_modify(ui_Create_Uesr_Button0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_Create_Uesr_Label2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_screen_change(&ui_Login, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Login_screen_init);
    }
}

/************************* RS485 *******************************/

// Event handler for navigating to the RS485 screen
void ui_event_RS485(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the event is a click
    if(event_code == LV_EVENT_CLICKED) {
        // Change screen to the RS485 screen and start the RS485 task
        _ui_screen_change(&ui_Main_RS485, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Main_RS485_screen_init);
        xTaskCreate(rs485_task, "rs485_task", 3 * 1024, NULL, 2, &rs485_TaskHandle);
    }
}

// Event handler for stopping RS485 and deleting the RS485 task
void ui_event_RS485_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the event is a click
    if(event_code == LV_EVENT_CLICKED) {
        // Change screen back to the main screen and close RS485
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Main_screen_init);
        DEV_UART_Delete();  // Delete UART for RS485 communication
        vTaskDelete(rs485_TaskHandle);  // Delete the RS485 task
        rs485_TaskHandle = NULL;  // Reset the task handle
    }
}

// Event handler for the RS485 send area (keyboard interaction)
void ui_event_RS485_Send_Area(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the send area gains focus
    if(event_code == LV_EVENT_FOCUSED) {
        // Remove the hidden flag from the keyboard and set the keyboard target to the send area
        _ui_flag_modify(ui_RS485_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_RS485_Keyboard1, ui_RS485_Send_Area);
        
        lv_textarea_set_placeholder_text(ui_Create_Uesr_Name, ""); 
        lv_obj_set_style_bg_opa(ui_Create_Uesr_Name, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
        
    }
    // Triggered when the send area loses focus
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_RS485_Keyboard1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);  // Add the hidden flag back to keyboard
        
        lv_textarea_set_placeholder_text(ui_Create_Uesr_Name, "Send..."); 
        lv_obj_set_style_bg_opa(ui_Create_Uesr_Name, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        
    }
    // Triggered when the send area is ready to send data
    if(event_code == LV_EVENT_READY) {
        RS485Send(e);  // Call the function to send RS485 data
        
        lv_textarea_set_placeholder_text(ui_Create_Uesr_Name, "Send..."); 
        lv_obj_set_style_bg_opa(ui_Create_Uesr_Name, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
      
    }
}

// Event handler for RS485 baud rate settings button (toggle visibility)
void ui_event_RS485_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the button is pressed
    if(event_code == LV_EVENT_PRESSED) {
        // Toggle visibility of baud rate roller and save button
        _ui_flag_modify(ui_RS485_Roller1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
        _ui_flag_modify(ui_RS485_Button4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);
    }
}

// Event handler to save the selected RS485 baud rate
void ui_event_RS485_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the button is clicked
    if(event_code == LV_EVENT_CLICKED) {
        RS485Savebaud(e);  // Save the selected baud rate
        _ui_flag_modify(ui_RS485_Roller1, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);  // Hide the baud rate roller
        _ui_flag_modify(ui_RS485_Button4, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);  // Hide the save button
    }
}

// Event handler to clear RS485 received data
void ui_event_RS485_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the button is clicked
    if(event_code == LV_EVENT_CLICKED) {
        RS485Clear(e);  // Clear the received RS485 data
    }
}


/************************* CAN *******************************/

// Event handler for CAN screen navigation
void ui_event_CAN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the event is a click
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main_CAN, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Main_CAN_screen_init);  // Change screen to CAN screen
        // Start the CAN task
        xTaskCreate(can_task, "can_task", 3 * 1024, NULL, 2, &can_TaskHandle);
    }
}

// Event handler for stopping CAN and deleting the task
void ui_event_CAN_Button1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Main_screen_init);  // Change screen to main screen
        // Uninstall CAN driver and delete task
        can_uninstall();  // Uninstall CAN driver
        vTaskDelete(can_TaskHandle);  // Delete the CAN task
        can_TaskHandle = NULL;  // Reset task handle
    }
}

// Event handler for CAN ID input field (keyboard interaction)
void ui_event_CAN_Send_ID(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the CAN ID field gains focus
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_CAN_Keyboard0,  ui_CAN_Send_ID);  // Set keyboard target to CAN ID field
        _ui_flag_modify(ui_CAN_Keyboard0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);  // Show keyboard

        lv_obj_set_style_bg_opa(ui_CAN_Send_Len, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_Len, "Length...");
        lv_obj_set_style_bg_opa(ui_CAN_Send_Data, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_Data, "Data(Hex)...");
        lv_obj_set_style_bg_opa(ui_CAN_Send_ID, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_ID, "");
    }
    // Triggered when the CAN ID field loses focus
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_CAN_Keyboard0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);  // Hide keyboard
        lv_obj_set_style_bg_opa(ui_CAN_Send_ID, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_ID, "ID...");
    }
    // Triggered when the input is ready
    if(event_code == LV_EVENT_READY) {
        _ui_state_modify(ui_CAN_Send_ID, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);  // Remove focus from CAN ID
        _ui_state_modify(ui_CAN_Send_Len, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);  // Focus on length field
        _ui_keyboard_set_target(ui_CAN_Keyboard0,  ui_CAN_Send_Len);  // Set keyboard target to length field
        lv_obj_set_style_bg_opa(ui_CAN_Send_ID, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_ID, "ID...");
        lv_obj_set_style_bg_opa(ui_CAN_Send_Len, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_Len, "");
    }
}

// Event handler for CAN message length input field (keyboard interaction)
void ui_event_CAN_Send_Len(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the length field gains focus
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_keyboard_set_target(ui_CAN_Keyboard0,  ui_CAN_Send_Len);  // Set keyboard target to length field
        _ui_flag_modify(ui_CAN_Keyboard0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);  // Show keyboard
        
        lv_obj_set_style_bg_opa(ui_CAN_Send_ID, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_ID, "ID...");
        lv_obj_set_style_bg_opa(ui_CAN_Send_Data, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_Data, "Data(Hex)...");

        lv_obj_set_style_bg_opa(ui_CAN_Send_Len, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_Len, "");  
    }
    // Triggered when the length field loses focus
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_CAN_Keyboard0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);  // Hide keyboard
        
        lv_obj_set_style_bg_opa(ui_CAN_Send_Len, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_Len, "Length...");
    }
    // Triggered when the input is ready
    if(event_code == LV_EVENT_READY) {
        _ui_state_modify(ui_CAN_Send_Len, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);  // Remove focus from length field
        _ui_state_modify(ui_CAN_Send_Data, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);  // Focus on data field
        _ui_keyboard_set_target(ui_CAN_Keyboard0,  ui_CAN_Send_Data);  // Set keyboard target to data field
        
        lv_obj_set_style_bg_opa(ui_CAN_Send_Len, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_Len, "Length...");
        lv_obj_set_style_bg_opa(ui_CAN_Send_Data, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_Data, "");  
    }
}

// Event handler for CAN message data input field (keyboard interaction)
void ui_event_CAN_Send_Data(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the data field gains focus
    if(event_code == LV_EVENT_FOCUSED) {
        _ui_flag_modify(ui_CAN_Keyboard0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);  // Show keyboard
        _ui_keyboard_set_target(ui_CAN_Keyboard0,  ui_CAN_Send_Data);  // Set keyboard target to data field
        
        lv_obj_set_style_bg_opa(ui_CAN_Send_ID, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_ID, "ID...");
        lv_obj_set_style_bg_opa(ui_CAN_Send_Len, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_Len, "Length...");
        lv_obj_set_style_bg_opa(ui_CAN_Send_Data, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_Data, "");  
    }
    // Triggered when the data field loses focus
    if(event_code == LV_EVENT_DEFOCUSED) {
        _ui_flag_modify(ui_CAN_Keyboard0, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);  // Hide keyboard
        
        lv_obj_set_style_bg_opa(ui_CAN_Send_Data, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_Data, "Data(Hex)...");
    }
    // Triggered when the input is ready
    if(event_code == LV_EVENT_READY) {
        CANSend1(e);  // Send the CAN message data

        lv_obj_set_style_bg_opa(ui_CAN_Send_ID, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_ID, "ID...");
        lv_obj_set_style_bg_opa(ui_CAN_Send_Len, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_Len, "Length...");
        lv_obj_set_style_bg_opa(ui_CAN_Send_Data, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
        lv_textarea_set_placeholder_text(ui_CAN_Send_Data, "Data(Hex)...");
    }
}

// Event handler for toggling visibility of baud rate selection interface
void ui_event_CAN_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the button is pressed
    if(event_code == LV_EVENT_PRESSED) {
        _ui_flag_modify(ui_CAN_Roller, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);  // Toggle visibility of baud rate roller
        _ui_flag_modify(ui_CAN_Button3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_TOGGLE);  // Toggle visibility of save button
    }
}

// Event handler for saving the selected CAN baud rate
void ui_event_CAN_Button3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the button is clicked
    if(event_code == LV_EVENT_CLICKED) {
        CANSavebaud(e);  // Save the selected CAN baud rate
        _ui_flag_modify(ui_CAN_Roller, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);  // Hide baud rate roller
        _ui_flag_modify(ui_CAN_Button3, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);  // Hide save button
    }
}

// Event handler to clear the CAN message data
void ui_event_CAN_Button4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the button is clicked
    if(event_code == LV_EVENT_CLICKED) {
        CANClear(e);  // Clear the CAN data
    }
}


/********* PWM **********/

// Event handler for navigating to the PWM screen
void ui_event_PWM(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the event is a click
    if(event_code == LV_EVENT_CLICKED) {
        // Change screen to the PWM control screen
        _ui_screen_change(&ui_Main_PWM, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Main_PWM_screen_init);
    }
}

// Event handler for handling interactions with the PWM Arc control (long press and click)
void ui_event_PWM_Arc0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    // Triggered during a long press repeat on the Arc control
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        // Clear the text value of the label next to the arc control
        _ui_arc_set_text_value(ui_PWM_Label0, target, "", "");

        // Get the current text of the label, then update the other label
        const char *text = lv_label_get_text(ui_PWM_Label0);
        lv_label_set_text(ui_PWM_Label1, text);

        // Get the value of the arc and set the value on the corresponding slider
        int16_t value = lv_arc_get_value(ui_PWM_Arc0);
        lv_slider_set_value(ui_PWM_Slider0, value, LV_ANIM_ON);

        // Set the PWM value by adjusting it (100 - arc value)
        IO_EXTENSION_Pwm_Output(100 - value);
        DEV_SET_PWM(100 - value);
    }
    
    // Triggered when the Arc control is clicked
    if(event_code == LV_EVENT_CLICKED) {
        // Clear the text value of the label next to the arc control
        _ui_arc_set_text_value(ui_PWM_Label0, target, "", "");

        // Get the current text of the label, then update the other label
        const char *text = lv_label_get_text(ui_PWM_Label0);
        lv_label_set_text(ui_PWM_Label1, text);

        // Get the value of the arc and set the value on the corresponding slider
        int16_t value = lv_arc_get_value(ui_PWM_Arc0);
        lv_slider_set_value(ui_PWM_Slider0, value, LV_ANIM_ON);

        // Set the PWM value by adjusting it (100 - arc value)
        IO_EXTENSION_Pwm_Output(100 - value);
        DEV_SET_PWM(100 - value);
    }
}

// Event handler for the PWM slider (long press and click)
void ui_event_PWM_Slider0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    // Triggered during a long press repeat on the slider control
    if(event_code == LV_EVENT_LONG_PRESSED_REPEAT) {
        // Clear the text value of the label next to the slider
        _ui_slider_set_text_value(ui_PWM_Label1, target, "", "");

        // Get the current text of the label, then update the other label
        const char *text = lv_label_get_text(ui_PWM_Label1);
        lv_label_set_text(ui_PWM_Label0, text);

        // Get the value of the slider and set the value on the corresponding arc control
        int16_t value = lv_slider_get_value(ui_PWM_Slider0);
        lv_arc_set_value(ui_PWM_Arc0, value);

        // Set the PWM value by adjusting it (100 - slider value)
        IO_EXTENSION_Pwm_Output(100 - value);
        DEV_SET_PWM(100 - value);
    }

    // Triggered when the slider is clicked
    if(event_code == LV_EVENT_CLICKED) {
        // Clear the text value of the label next to the slider
        _ui_slider_set_text_value(ui_PWM_Label1, target, "", "");

        // Get the current text of the label, then update the other label
        const char *text = lv_label_get_text(ui_PWM_Label1);
        lv_label_set_text(ui_PWM_Label0, text);

        // Get the value of the slider and set the value on the corresponding arc control
        int16_t value = lv_slider_get_value(ui_PWM_Slider0);
        lv_arc_set_value(ui_PWM_Arc0, value);

        // Set the PWM value by adjusting it (100 - slider value)
        IO_EXTENSION_Pwm_Output(100 - value);
        DEV_SET_PWM(100 - value);
    }
}


// Event handler for the first PWM switch (Switch1)
void ui_event_PWM_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    // Triggered when the switch state changes to "checked"
    if(event_code == LV_EVENT_VALUE_CHANGED && lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // Disable other switches to prevent conflicts
        _ui_state_modify(ui_PWM_Switch2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_PWM_Switch3, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);

        // Set values for the Arc, Slider, and Labels to indicate PWM level
        lv_arc_set_value(ui_PWM_Arc0, 33);
        lv_slider_set_value(ui_PWM_Slider0, 33, LV_ANIM_ON);
        lv_label_set_text(ui_PWM_Label0, "33");
        lv_label_set_text(ui_PWM_Label1, "33");

        // Set the PWM output to 33
        IO_EXTENSION_Pwm_Output(100 - 33);
        DEV_SET_PWM(100 - 33);
    }

    // Triggered when the switch state changes to "unchecked"
    if(event_code == LV_EVENT_VALUE_CHANGED && !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // Enable other switches to allow interaction
        _ui_state_modify(ui_PWM_Switch3, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_PWM_Switch2, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);

        // Reset all values to 50
        lv_arc_set_value(ui_PWM_Arc0, 50);
        lv_slider_set_value(ui_PWM_Slider0, 50, LV_ANIM_ON);
        lv_label_set_text(ui_PWM_Label0, "50");
        lv_label_set_text(ui_PWM_Label1, "50");

        // Set PWM output to 100 (off)
        IO_EXTENSION_Pwm_Output(50);
        DEV_SET_PWM(50);
    }
}

// Event handler for the second PWM switch (Switch2)
void ui_event_PWM_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    // Triggered when the switch state changes to "checked"
    if(event_code == LV_EVENT_VALUE_CHANGED && lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // Disable other switches to prevent conflicts
        _ui_state_modify(ui_PWM_Switch3, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_PWM_Switch1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);

        // Set values for the Arc, Slider, and Labels to indicate PWM level
        lv_arc_set_value(ui_PWM_Arc0, 66);
        lv_slider_set_value(ui_PWM_Slider0, 66, LV_ANIM_ON);
        lv_label_set_text(ui_PWM_Label0, "66");
        lv_label_set_text(ui_PWM_Label1, "66");

        // Set the PWM output to 66
        IO_EXTENSION_Pwm_Output(100 - 66);
        DEV_SET_PWM(100 - 66);
    }

    // Triggered when the switch state changes to "unchecked"
    if(event_code == LV_EVENT_VALUE_CHANGED && !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // Enable other switches to allow interaction
        _ui_state_modify(ui_PWM_Switch3, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_PWM_Switch1, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);

        // Reset all values to 50
        lv_arc_set_value(ui_PWM_Arc0, 50);
        lv_slider_set_value(ui_PWM_Slider0, 50, LV_ANIM_ON);
        lv_label_set_text(ui_PWM_Label0, "50");
        lv_label_set_text(ui_PWM_Label1, "50");

        // Set PWM output to 100 (off)
        IO_EXTENSION_Pwm_Output(50);
        DEV_SET_PWM(50);
    }
}

// Event handler for the third PWM switch (Switch3)
void ui_event_PWM_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    // Triggered when the switch state changes to "checked"
    if(event_code == LV_EVENT_VALUE_CHANGED && lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // Disable other switches to prevent conflicts
        _ui_state_modify(ui_PWM_Switch2, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_PWM_Switch1, LV_STATE_DISABLED, _UI_MODIFY_STATE_ADD);

        // Set values for the Arc, Slider, and Labels to indicate PWM level
        lv_arc_set_value(ui_PWM_Arc0, 99);
        lv_slider_set_value(ui_PWM_Slider0, 99, LV_ANIM_ON);
        lv_label_set_text(ui_PWM_Label0, "99");
        lv_label_set_text(ui_PWM_Label1, "99");

        // Set the PWM output to 99
        IO_EXTENSION_Pwm_Output(100 - 99);
        DEV_SET_PWM(100 - 99);
    }

    // Triggered when the switch state changes to "unchecked"
    if(event_code == LV_EVENT_VALUE_CHANGED && !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // Enable other switches to allow interaction
        _ui_state_modify(ui_PWM_Switch2, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_PWM_Switch1, LV_STATE_DISABLED, _UI_MODIFY_STATE_REMOVE);

        // Reset all values to 50
        lv_arc_set_value(ui_PWM_Arc0, 50);
        lv_slider_set_value(ui_PWM_Slider0, 50, LV_ANIM_ON);
        lv_label_set_text(ui_PWM_Label0, "50");
        lv_label_set_text(ui_PWM_Label1, "50");

        // Set PWM output to 100 (off)
        IO_EXTENSION_Pwm_Output(50);
        DEV_SET_PWM(50);
    }
}


// Event handler for the PWM Button (Button0)
void ui_event_PWM_Button0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the button is clicked
    if(event_code == LV_EVENT_CLICKED) {
        // Change the screen to the main screen with a fade animation
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Main_screen_init);
    }
}


/******************WIFI*********************** */

// Event handler for the Wifi button (WiFi settings screen)
void ui_event_Wifi(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the Wifi button is clicked
    if(event_code == LV_EVENT_CLICKED) {
        // Change the screen to the Wifi settings screen with a fade animation
        _ui_screen_change(&ui_Main_WIFI, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Main_WIFI_screen_init);
    }
}

// Event handler for the Wifi back button (returns to main screen)
void ui_event_WIFI_Button0(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the back button is clicked
    if(event_code == LV_EVENT_CLICKED) {
        // Change the screen back to the main screen with a fade animation
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Main_screen_init);
    }
}

// Event handler for toggling the Wifi switch (open/close Wifi functionality)
void ui_event_WIFI_OPEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    // When the switch is turned ON (checked state)
    if(event_code == LV_EVENT_VALUE_CHANGED && lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // Remove the hidden flag from the Wifi scan list (show the list)
        _ui_flag_modify(ui_WIFI_SCAN_List, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE); 
        WIFIOPEN(e);  // Open Wifi functionality
    }
    
    // When the switch is turned OFF (unchecked state)
    if(event_code == LV_EVENT_VALUE_CHANGED && !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // Add the hidden flag to the Wifi scan list (hide the list)
        _ui_flag_modify(ui_WIFI_SCAN_List, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        WIFICLOSE(e);  // Close Wifi functionality
    }
}

// Event handler for selecting a Wifi network from the scan list
void ui_WIFI_list_event_cb(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // When a network in the list is pressed
    if(event_code == LV_EVENT_PRESSED) {
        
        // Show the Wifi details window and hide the password error window
        _ui_flag_modify(ui_WIFI_Details_Win, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_WIFI_PWD_Error, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        
        // Get the button that was pressed (the selected Wifi network)
        WIFI_List_Button = lv_event_get_target(e);  
        wifi_index = (int)lv_event_get_user_data(e);  // Get the index of the selected Wifi network
        printf("index:%d\r\n",wifi_index);

        // If the selected network is the currently connected one, show the IP address
        if (WIFI_CONNECTION == wifi_index) {
            _ui_flag_modify(ui_WIFI_IP, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);  
        } else {
            // Otherwise, hide the IP address display
            _ui_flag_modify(ui_WIFI_IP, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        }
        
        // Clear the password input field
        lv_textarea_set_text(ui_WIFI_INPUT_PWD, "");

        // Display Wifi details window
        _ui_flag_modify(ui_WIFI_Details_Win, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        
        static char result[100];
        // Display SSID
        sprintf(result, "SSID %s", ap_info[wifi_index].ssid);
        lv_label_set_text(ui_WIFI_Name,result);

        // Print authentication mode (e.g., WPA2, WPA3)
        print_auth_mode(ap_info[wifi_index].authmode);

        // If the network is not using WEP, display cipher types
        if (ap_info[wifi_index].authmode != WIFI_AUTH_WEP) {
            print_cipher_type(ap_info[wifi_index].pairwise_cipher, ap_info[wifi_index].group_cipher);
        }

        // Display the Wifi channel
        sprintf(result, "Channel \t\t%d", ap_info[wifi_index].primary);
        lv_label_set_text(ui_WIFI_Channel,result);
    }
}


/******************WIFI CONNECTION HANDLERS*********************** */

// Event handler for the Wifi connection button (shows the password input field)
void ui_event_WIFI_Connection_BUTTON(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the connection button is clicked
    if(event_code == LV_EVENT_CLICKED) {
        // Show the password input field
        _ui_flag_modify(ui_WIFI_INPUT_PWD, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// Event handler for the Wifi password input field (handles keyboard interactions)
void ui_event_WIFI_INPUT_PWD(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the password input field loses focus
    if(event_code == LV_EVENT_DEFOCUSED) {
        // Hide the keyboard and the password input field when it loses focus
        _ui_flag_modify(ui_WIFI_INPUT_KEYBOARD, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_WIFI_INPUT_PWD, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
    
    // Triggered when the password input field gains focus
    if(event_code == LV_EVENT_FOCUSED) {
        // Set the keyboard to target the password input field
        _ui_keyboard_set_target(ui_WIFI_INPUT_KEYBOARD, ui_WIFI_INPUT_PWD);
        // Show the keyboard and hide the password input field
        _ui_flag_modify(ui_WIFI_INPUT_KEYBOARD, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
    
    // Triggered when the user has finished entering the password
    if(event_code == LV_EVENT_READY) {
        // Attempt to connect to Wifi with the provided password
        WIFIConnection(e);
        // Hide the keyboard and password field after connection attempt
        _ui_flag_modify(ui_WIFI_INPUT_KEYBOARD, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        _ui_flag_modify(ui_WIFI_INPUT_PWD, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
        // Show the waiting for connection window
        _ui_flag_modify(ui_WIFI_Wait_CONNECTION, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// Event handler for the eye icon (toggles password visibility)
void ui_event_WIFI_EYE(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the eye icon is clicked
    if(event_code == LV_EVENT_CLICKED) {
        // Toggle password visibility
        WIFI_DIS_PWD = !WIFI_DIS_PWD;
        // Update the password input field based on the toggle state
        lv_textarea_set_password_mode(ui_WIFI_INPUT_PWD, WIFI_DIS_PWD);
        // Show the keyboard and password field
        _ui_flag_modify(ui_WIFI_INPUT_KEYBOARD, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_WIFI_INPUT_PWD, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// Event handler for the back button in the Wifi settings (returns to the main screen)
void ui_event_WIFI_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the back button is clicked
    if(event_code == LV_EVENT_CLICKED) {
        // Change the screen back to the main screen with a fade animation
        _ui_screen_change(&ui_Main, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_Main_screen_init);
    }
}


/******************WIFI AP HANDLERS*********************** */

// Event handler for the AP name input field
void ui_event_WIFI_AP_NAME(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the AP name input field gains focus
    if(event_code == LV_EVENT_FOCUSED) {
        // Set the keyboard to target the AP name field
        _ui_keyboard_set_target(ui_WIFI_AP_Keyboard, ui_WIFI_AP_NAME);
        // Show the keyboard and hide the input error message
        _ui_flag_modify(ui_WIFI_AP_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_WIFI_AP_INPUT_ERROR, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }

    // Triggered when the AP name input field loses focus
    if(event_code == LV_EVENT_DEFOCUSED) {
        // Hide the keyboard when the field loses focus
        _ui_flag_modify(ui_WIFI_AP_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }

    // Triggered when the user finishes entering the AP name
    if(event_code == LV_EVENT_READY) {
        // Change focus to the password field after entering the AP name
        _ui_state_modify(ui_WIFI_AP_NAME, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        _ui_state_modify(ui_WIFI_AP_Password, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
        // Set the keyboard to target the password input field
        _ui_keyboard_set_target(ui_WIFI_AP_Keyboard, ui_WIFI_AP_Password);
    }
}

// Event handler for the AP password input field
void ui_event_WIFI_AP_Password(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the password input field gains focus
    if(event_code == LV_EVENT_FOCUSED) {
        // Set the keyboard to target the password field
        _ui_keyboard_set_target(ui_WIFI_AP_Keyboard, ui_WIFI_AP_Password);
        // Show the keyboard and hide the input error message
        _ui_flag_modify(ui_WIFI_AP_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_WIFI_AP_INPUT_ERROR, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }

    // Triggered when the password input field loses focus
    if(event_code == LV_EVENT_DEFOCUSED) {
        // Hide the keyboard when the field loses focus
        _ui_flag_modify(ui_WIFI_AP_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }

    // Triggered when the user finishes entering the password
    if(event_code == LV_EVENT_READY) {
        // Change focus to the AP channel field after entering the password
        _ui_state_modify(ui_WIFI_AP_Channel, LV_STATE_FOCUSED, _UI_MODIFY_STATE_ADD);
        _ui_state_modify(ui_WIFI_AP_Password, LV_STATE_FOCUSED, _UI_MODIFY_STATE_REMOVE);
        // Set the keyboard to target the AP channel input field
        _ui_keyboard_set_target(ui_WIFI_AP_Keyboard, ui_WIFI_AP_Channel);
    }
}

// Event handler for the eye icon (toggles the visibility of the AP password)
void ui_event_WIFI_AP_EYE(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the eye icon is clicked
    if(event_code == LV_EVENT_CLICKED) {
        // Toggle password visibility
        WIFI_AP_PWD = !WIFI_AP_PWD;
        // Update the password input field based on the visibility state
        lv_textarea_set_password_mode(ui_WIFI_AP_Password, WIFI_AP_PWD);
        // Show the keyboard and password input field
        _ui_flag_modify(ui_WIFI_AP_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
    }
}

// Event handler for the AP channel input field
void ui_event_WIFI_AP_Channel(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    // Triggered when the AP channel input field gains focus
    if(event_code == LV_EVENT_FOCUSED) {
        // Set the keyboard to target the AP channel field
        _ui_keyboard_set_target(ui_WIFI_AP_Keyboard, ui_WIFI_AP_Channel);
        // Show the keyboard and hide the input error message
        _ui_flag_modify(ui_WIFI_AP_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_flag_modify(ui_WIFI_AP_INPUT_ERROR, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }

    // Triggered when the AP channel input field loses focus
    if(event_code == LV_EVENT_DEFOCUSED) {
        // Hide the keyboard when the field loses focus
        _ui_flag_modify(ui_WIFI_AP_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }

    // Triggered when the user finishes entering the AP channel
    if(event_code == LV_EVENT_READY) {
        // Hide the keyboard after the user is done entering the channel
        _ui_flag_modify(ui_WIFI_AP_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

// Event handler for toggling the Wifi AP state (open/close)
void ui_event_WIFI_AP_OPEN(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    // Triggered when the toggle state of the AP open button changes
    if(event_code == LV_EVENT_VALUE_CHANGED && lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // If checked, open the Wifi AP
        WIFIAPOPEN(e);
    }

    if(event_code == LV_EVENT_VALUE_CHANGED && !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        // If unchecked, close the Wifi AP
        WIFIAPCLOSE(e);
    }
}

/********************* UI Initialization *********************/

// Function to initialize the UI and set up the screens
void ui_init(void)
{
    // Get the default display object
    lv_disp_t * dispp = lv_disp_get_default();
    
    // Initialize the default theme with specific colors (blue and red) and default font
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    // Apply the theme to the display
    lv_disp_set_theme(dispp, theme);
    
    // Initialize different screens
    ui_Login_screen_init();      // Initialize the Login screen
    ui_Create_Uesr_screen_init(); // Initialize the Create User screen
    ui_Main_screen_init();        // Initialize the Main screen
    ui_Main_RS485_screen_init();  // Initialize the Main RS485 screen
    ui_Main_CAN_screen_init();    // Initialize the Main CAN screen
    ui_Main_PWM_screen_init();    // Initialize the Main PWM screen
    ui_Main_WIFI_screen_init();   // Initialize the Main WIFI screen

    // Create an object for initial actions (e.g., for performing actions on initialization)
    ui____initial_actions0 = lv_obj_create(NULL);
    
    // Load the Login screen as the starting screen
    lv_disp_load_scr(ui_Login);
}
