// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: sq_ui

#include "../ui.h"

// Function to initialize the 'Create User' screen
void ui_Create_Uesr_screen_init(void)
{
    // Create the main 'Create User' object
    ui_Create_Uesr = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Create_Uesr, LV_OBJ_FLAG_SCROLLABLE);                                        // Disable scrolling for the main screen
    lv_obj_set_style_bg_img_src(ui_Create_Uesr, &ui_img_log_on_png, LV_PART_MAIN | LV_STATE_DEFAULT); // Set background image for the main screen

    // Create the panel inside the 'Create User' screen
    ui_Create_Uesr_Panel0 = lv_obj_create(ui_Create_Uesr);
    lv_obj_set_width(ui_Create_Uesr_Panel0, 379);                                                                  // Set the panel width to 340px
    lv_obj_set_height(ui_Create_Uesr_Panel0, 231);                                                                 // Set the panel height to 231px
    lv_obj_set_x(ui_Create_Uesr_Panel0, 0);                                                                        // Set panel's X position to 0 (centered)
    lv_obj_set_y(ui_Create_Uesr_Panel0, -100);                                                                     // Set panel's Y position to -100
    lv_obj_set_align(ui_Create_Uesr_Panel0, LV_ALIGN_CENTER);                                                      // Align the panel to the center of the screen
    lv_obj_clear_flag(ui_Create_Uesr_Panel0, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling for the panel
    lv_obj_set_style_bg_color(ui_Create_Uesr_Panel0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color to white
    lv_obj_set_style_bg_opa(ui_Create_Uesr_Panel0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set panel background opacity to 0 (transparent)
    lv_obj_set_style_border_color(ui_Create_Uesr_Panel0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color to black
    lv_obj_set_style_border_opa(ui_Create_Uesr_Panel0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity to 0 (transparent)
    lv_obj_set_style_text_font(ui_Create_Uesr_Panel0, &ui_font_Chinese_Font, LV_PART_MAIN | LV_STATE_DEFAULT);     // Set the font to Chinese

    // Create the label for the "New User" text
    ui_Create_Uesr_Label0 = lv_label_create(ui_Create_Uesr_Panel0);
    lv_obj_set_width(ui_Create_Uesr_Label0, LV_SIZE_CONTENT);                                                    // Set label width to fit the content
    lv_obj_set_height(ui_Create_Uesr_Label0, LV_SIZE_CONTENT);                                                   // Set label height to fit the content
    lv_obj_set_x(ui_Create_Uesr_Label0, 0);                                                                      // Set X position to 0 (centered)
    lv_obj_set_y(ui_Create_Uesr_Label0, -90);                                                                    // Set Y position to -90px
    lv_obj_set_align(ui_Create_Uesr_Label0, LV_ALIGN_LEFT_MID);                                                  // Align label to the left center
    lv_label_set_text(ui_Create_Uesr_Label0, "New User");                                                        // Set label text to "New User"
    lv_obj_set_style_text_color(ui_Create_Uesr_Label0, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_Create_Uesr_Label0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to 255 (fully opaque)
    lv_obj_set_style_text_font(ui_Create_Uesr_Label0, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create the label for the "New Password" text
    ui_Create_Uesr_Label1 = lv_label_create(ui_Create_Uesr_Panel0);
    lv_obj_set_width(ui_Create_Uesr_Label1, LV_SIZE_CONTENT);                                                    // Set label width to fit the content
    lv_obj_set_height(ui_Create_Uesr_Label1, LV_SIZE_CONTENT);                                                   // Set label height to fit the content
    lv_obj_set_x(ui_Create_Uesr_Label1, 0);                                                                      // Set X position to 0 (centered)
    lv_obj_set_y(ui_Create_Uesr_Label1, 10);                                                                     // Set Y position to 10px
    lv_obj_set_align(ui_Create_Uesr_Label1, LV_ALIGN_LEFT_MID);                                                  // Align label to the left center
    lv_label_set_text(ui_Create_Uesr_Label1, "New Password");                                                    // Set label text to "New Password"
    lv_obj_set_style_text_color(ui_Create_Uesr_Label1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_Create_Uesr_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to 255 (fully opaque)
    lv_obj_set_style_text_font(ui_Create_Uesr_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create a text area for entering the username
    ui_Create_Uesr_Name = lv_textarea_create(ui_Create_Uesr_Panel0);
    lv_obj_set_width(ui_Create_Uesr_Name, 326);                                                                  // Set the width of the username input field
    lv_obj_set_height(ui_Create_Uesr_Name, LV_SIZE_CONTENT);                                                     // Set height based on content (70px)
    lv_obj_set_x(ui_Create_Uesr_Name, -10);                                                                       // Set X position to 15px from the left
    lv_obj_set_y(ui_Create_Uesr_Name, -50);                                                                      // Set Y position to -50px
    lv_obj_set_align(ui_Create_Uesr_Name, LV_ALIGN_RIGHT_MID);                                                   // Align to the right center
    lv_textarea_set_max_length(ui_Create_Uesr_Name, 20);                                                         // Set maximum input length to 20 characters
    lv_textarea_set_placeholder_text(ui_Create_Uesr_Name, "Enter username...");                                  // Set placeholder text
    lv_textarea_set_one_line(ui_Create_Uesr_Name, true);                                                         // Allow only one line of text
    lv_obj_set_style_text_color(ui_Create_Uesr_Name, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set text color to white
    lv_obj_set_style_text_opa(ui_Create_Uesr_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set text opacity to fully opaque
    lv_obj_set_style_bg_color(ui_Create_Uesr_Name, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color to a dark blue
    lv_obj_set_style_bg_opa(ui_Create_Uesr_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity to fully opaque
    lv_obj_set_style_border_color(ui_Create_Uesr_Name, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color to black
    lv_obj_set_style_border_opa(ui_Create_Uesr_Name, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity to fully transparent

    lv_obj_set_style_bg_color(ui_Create_Uesr_Name, lv_color_hex(0xAAAAAA), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Create_Uesr_Name, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Create_Uesr_Name, LV_GRAD_DIR_VER, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Create a text area for entering the password
    ui_Create_Uesr_Password = lv_textarea_create(ui_Create_Uesr_Panel0);
    lv_obj_set_width(ui_Create_Uesr_Password, 327);                                                                  // Set the width of the password input field
    lv_obj_set_height(ui_Create_Uesr_Password, LV_SIZE_CONTENT);                                                     // Set height based on content (70px)
    lv_obj_set_x(ui_Create_Uesr_Password, -10);                                                                       // Set X position to 15px from the left
    lv_obj_set_y(ui_Create_Uesr_Password, 50);                                                                       // Set Y position to 50px
    lv_obj_set_align(ui_Create_Uesr_Password, LV_ALIGN_RIGHT_MID);                                                   // Align to the right center
    lv_textarea_set_max_length(ui_Create_Uesr_Password, 20);                                                         // Set maximum input length to 20 characters
    lv_textarea_set_placeholder_text(ui_Create_Uesr_Password, "Enter password...");                                  // Set placeholder text
    lv_textarea_set_one_line(ui_Create_Uesr_Password, true);                                                         // Allow only one line of text
    lv_textarea_set_password_mode(ui_Create_Uesr_Password, true);                                                    // Set password input mode (hide characters)
    lv_obj_add_flag(ui_Create_Uesr_Password, LV_OBJ_FLAG_SCROLL_WITH_ARROW);                                         // Allow scrolling with the arrow keys
    lv_obj_clear_flag(ui_Create_Uesr_Password, LV_OBJ_FLAG_SCROLL_CHAIN);                                            // Disable scroll chain functionality
    lv_obj_set_style_text_color(ui_Create_Uesr_Password, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set text color to white
    lv_obj_set_style_text_opa(ui_Create_Uesr_Password, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set text opacity to fully opaque
    lv_obj_set_style_bg_color(ui_Create_Uesr_Password, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color to dark blue
    lv_obj_set_style_bg_opa(ui_Create_Uesr_Password, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity to fully opaque
    lv_obj_set_style_border_color(ui_Create_Uesr_Password, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color to black
    lv_obj_set_style_border_opa(ui_Create_Uesr_Password, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity to fully transparent

    lv_obj_set_style_bg_color(ui_Create_Uesr_Password, lv_color_hex(0xAAAAAA), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Create_Uesr_Password, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Create_Uesr_Password, LV_GRAD_DIR_VER, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Create an eye icon button for showing/hiding the password
    ui_Create_Uesr_Pwd_EYE = lv_img_create(ui_Create_Uesr_Password);
    lv_img_set_src(ui_Create_Uesr_Pwd_EYE, &ui_img_eye_png);                                  // Set the image source to an eye icon (password visibility toggle)
    lv_obj_set_width(ui_Create_Uesr_Pwd_EYE, LV_SIZE_CONTENT);                                // Set width based on content (34px)
    lv_obj_set_height(ui_Create_Uesr_Pwd_EYE, LV_SIZE_CONTENT);                               // Set height based on content (20px)
    lv_obj_set_align(ui_Create_Uesr_Pwd_EYE, LV_ALIGN_RIGHT_MID);                             // Align the eye icon to the right center of the password field
    lv_obj_add_flag(ui_Create_Uesr_Pwd_EYE, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST); // Make the eye icon clickable and enable advanced hit-testing
    lv_obj_clear_flag(ui_Create_Uesr_Pwd_EYE, LV_OBJ_FLAG_SCROLLABLE);                        // Disable scrolling for the eye icon

    // Create a keyboard for user input
    ui_Create_Uesr_Keyboard0 = lv_keyboard_create(ui_Create_Uesr);
    lv_obj_set_width(ui_Create_Uesr_Keyboard0, lv_pct(100));                                        // Set width to 100% of the screen
    lv_obj_set_height(ui_Create_Uesr_Keyboard0, lv_pct(50));                                        // Set height to 50% of the screen
    lv_obj_set_align(ui_Create_Uesr_Keyboard0, LV_ALIGN_BOTTOM_MID);                                // Align the keyboard to the bottom center
    lv_obj_add_flag(ui_Create_Uesr_Keyboard0, LV_OBJ_FLAG_HIDDEN);                                  // Initially hide the keyboard
    lv_obj_set_style_text_font(ui_Create_Uesr_Keyboard0, &lv_font_montserrat_14, LV_STATE_DEFAULT); // Set text font for the keyboard
    lv_obj_set_style_bg_opa(ui_Create_Uesr_Keyboard0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);          // Set background opacity to fully transparent

    // Create a label for success message
    ui_Create_Uesr_Label2 = lv_label_create(ui_Create_Uesr_Panel0);
    lv_obj_set_width(ui_Create_Uesr_Label2, lv_pct(117));                                                        // Set label width to 100% of the panel
    lv_obj_set_height(ui_Create_Uesr_Label2, lv_pct(20));                                                        // Set label height to 20% of the panel
    lv_obj_set_x(ui_Create_Uesr_Label2, 0);                                                                      // Set X position to 0 (centered)
    lv_obj_set_y(ui_Create_Uesr_Label2, 20);                                                                     // Set Y position to 20px
    lv_obj_set_align(ui_Create_Uesr_Label2, LV_ALIGN_BOTTOM_MID);                                                // Align the label to the bottom center of the screen
    lv_label_set_text(ui_Create_Uesr_Label2, "Create successful, click login");                                  // Set label text
    lv_obj_add_flag(ui_Create_Uesr_Label2, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_CLICKABLE);                          // Make the label clickable but hidden by default
    lv_obj_set_style_text_color(ui_Create_Uesr_Label2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to red
    lv_obj_set_style_text_opa(ui_Create_Uesr_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully opaque
    lv_obj_set_style_text_align(ui_Create_Uesr_Label2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);   // Align the text in the center
    lv_obj_set_style_text_font(ui_Create_Uesr_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create a button that will be displayed on ui_Create_Uesr_Label2
    ui_Create_Uesr_Button0 = lv_btn_create(ui_Create_Uesr_Label2);
    lv_obj_set_width(ui_Create_Uesr_Button0, lv_pct(97));                                                          // Set the button width to 100% of its parent
    lv_obj_set_height(ui_Create_Uesr_Button0, lv_pct(100));                                                         // Set the button height to 100% of its parent
    lv_obj_set_align(ui_Create_Uesr_Button0, LV_ALIGN_CENTER);                                                      // Align the button to the center
    lv_obj_add_flag(ui_Create_Uesr_Button0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);                                           // Enable scroll on focus flag for the button
    lv_obj_clear_flag(ui_Create_Uesr_Button0, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrollable flag for the button
    lv_obj_set_style_bg_color(ui_Create_Uesr_Button0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set the background color to white
    lv_obj_set_style_bg_opa(ui_Create_Uesr_Button0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set the background opacity to 0 (transparent)
    lv_obj_set_style_border_color(ui_Create_Uesr_Button0, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set the border color to black
    lv_obj_set_style_border_opa(ui_Create_Uesr_Button0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set the border opacity to 0 (invisible)

    // Create a label that will be displayed on the UI
    ui_Create_Uesr_Label3 = lv_label_create(ui_Create_Uesr);
    lv_obj_set_x(ui_Create_Uesr_Label3, 0);                                                                      // Set the label's X position to 0
    lv_obj_set_y(ui_Create_Uesr_Label3, -12);                                                                    // Set the label's Y position to -12 (relative to the parent)
    lv_obj_set_align(ui_Create_Uesr_Label3, LV_ALIGN_CENTER);                                                    // Align the label to the center
    lv_label_set_text(ui_Create_Uesr_Label3, "Please enter your username first");                                // Set the text for the label
    lv_obj_add_flag(ui_Create_Uesr_Label3, LV_OBJ_FLAG_HIDDEN);                                                  // Initially hide the label
    lv_obj_set_style_text_color(ui_Create_Uesr_Label3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set the text color to red
    lv_obj_set_style_text_opa(ui_Create_Uesr_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set the text opacity to fully visible (255)
    lv_obj_set_style_text_font(ui_Create_Uesr_Label3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Add event callbacks for various UI elements
    lv_obj_add_event_cb(ui_Create_Uesr_Name, ui_event_Create_Uesr_Name, LV_EVENT_ALL, NULL);         // Add event callback for the username text area
    lv_obj_add_event_cb(ui_Create_Uesr_Pwd_EYE, ui_event_Create_Uesr_Pwd_EYE, LV_EVENT_ALL, NULL);   // Add event callback for the password eye icon
    lv_obj_add_event_cb(ui_Create_Uesr_Password, ui_event_Create_Uesr_Password, LV_EVENT_ALL, NULL); // Add event callback for the password text area

    // Set the keyboard to target the username text area
    lv_keyboard_set_textarea(ui_Create_Uesr_Keyboard0, ui_Create_Uesr_Name);

    // Add event callback for the button to handle interactions
    lv_obj_add_event_cb(ui_Create_Uesr_Button0, ui_event_Create_Uesr_Button0, LV_EVENT_ALL, NULL);
}
