// This file was generated by SquareLine Studio
// SquareLine Studio version: 1.5.0
// LVGL version: 8.3.11
// Project name: sq_ui

#include "../ui.h"

// Initialize the login screen UI elements
void ui_Login_screen_init(void)
{
    // Create the main login screen object
    ui_Login = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Login, LV_OBJ_FLAG_SCROLLABLE); // Disable scrolling for the main login screen

    // Create a panel for the login screen background
    ui_Login_Panel1 = lv_obj_create(ui_Login);
    lv_obj_set_width(ui_Login_Panel1, lv_pct(100));                                                          // Set the width of the panel to 100% of the parent
    lv_obj_set_height(ui_Login_Panel1, lv_pct(100));                                                         // Set the height of the panel to 100% of the parent
    lv_obj_set_align(ui_Login_Panel1, LV_ALIGN_CENTER);                                                      // Align the panel to the center of the parent
    lv_obj_clear_flag(ui_Login_Panel1, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling for the panel
    lv_obj_set_style_bg_img_src(ui_Login_Panel1, &ui_img_log_on_png, LV_PART_MAIN | LV_STATE_DEFAULT);       // Set the background image for the panel
    lv_obj_set_style_border_color(ui_Login_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set the border color to black
    lv_obj_set_style_border_opa(ui_Login_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity to 0 (invisible)
    lv_obj_set_style_text_font(ui_Login_Panel1, &ui_font_Chinese_Font, LV_PART_MAIN | LV_STATE_DEFAULT);     // Set the text font for the panel

    // Create the on-screen keyboard for user input
    ui_Login_Keyboard = lv_keyboard_create(ui_Login_Panel1);
    lv_obj_set_width(ui_Login_Keyboard, lv_pct(100));                                                        // Set the keyboard width to 100% of its parent
    lv_obj_set_height(ui_Login_Keyboard, lv_pct(50));                                                        // Set the keyboard height to 50% of its parent
    lv_obj_set_align(ui_Login_Keyboard, LV_ALIGN_BOTTOM_MID);                                                // Align the keyboard to the bottom center
    lv_obj_add_flag(ui_Login_Keyboard, LV_OBJ_FLAG_HIDDEN);                                                  // Initially hide the keyboard
    lv_obj_set_style_text_font(ui_Login_Keyboard, &lv_font_montserrat_14, LV_STATE_DEFAULT);                 // Set the text font for the keyboard
    lv_obj_set_style_bg_opa(ui_Login_Keyboard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set the keyboard background opacity to 0 (transparent)
    lv_obj_set_style_text_font(ui_Login_Keyboard, &lv_font_montserrat_14, LV_PART_ITEMS | LV_STATE_DEFAULT); // Set the text font for the keyboard items

    // Create a panel for the login form
    ui_Login_Panel2 = lv_obj_create(ui_Login_Panel1);
    lv_obj_set_width(ui_Login_Panel2, 340);                                                                  // Set the width of the panel
    lv_obj_set_height(ui_Login_Panel2, 231);                                                                 // Set the height of the panel
    lv_obj_set_x(ui_Login_Panel2, 0);                                                                        // Set the X position of the panel
    lv_obj_set_y(ui_Login_Panel2, -100);                                                                     // Set the Y position of the panel
    lv_obj_set_align(ui_Login_Panel2, LV_ALIGN_CENTER);                                                      // Align the panel to the center of its parent
    lv_obj_clear_flag(ui_Login_Panel2, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling for the panel
    lv_obj_set_style_bg_color(ui_Login_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set the background color to white
    lv_obj_set_style_bg_opa(ui_Login_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set background opacity to 0 (transparent)
    lv_obj_set_style_border_color(ui_Login_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set the border color to black
    lv_obj_set_style_border_opa(ui_Login_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity to 0 (invisible)

    // Create a label for the "New user" text on the login form
    ui_Login_Label0 = lv_label_create(ui_Login_Panel2);
    lv_obj_set_width(ui_Login_Label0, LV_SIZE_CONTENT);                                                    // Set the label width to the content size
    lv_obj_set_height(ui_Login_Label0, LV_SIZE_CONTENT);                                                   // Set the label height to the content size
    lv_obj_set_x(ui_Login_Label0, 0);                                                                      // Set the label's X position
    lv_obj_set_y(ui_Login_Label0, 90);                                                                     // Set the label's Y position
    lv_obj_set_align(ui_Login_Label0, LV_ALIGN_LEFT_MID);                                                  // Align the label to the left-middle of its parent
    lv_label_set_text(ui_Login_Label0, "New user");                                                        // Set the label text to "New user"
    lv_obj_add_flag(ui_Login_Label0, LV_OBJ_FLAG_CLICKABLE);                                               // Make the label clickable
    lv_obj_set_style_text_color(ui_Login_Label0, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set the label text color to blue
    lv_obj_set_style_text_opa(ui_Login_Label0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set the text opacity to fully visible (255)
    lv_obj_set_style_text_font(ui_Login_Label0, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create a label for the "User" text
    ui_Login_Label1 = lv_label_create(ui_Login_Panel2);
    lv_obj_set_width(ui_Login_Label1, LV_SIZE_CONTENT);                                                    // Set width to content size
    lv_obj_set_height(ui_Login_Label1, LV_SIZE_CONTENT);                                                   // Set height to content size
    lv_obj_set_x(ui_Login_Label1, -4);
    lv_obj_set_y(ui_Login_Label1, -92);                                                                   // Set Y position to -90 (above the panel)
    lv_obj_set_align(ui_Login_Label1, LV_ALIGN_LEFT_MID);                                                  // Align the label to the left middle of its parent
    lv_label_set_text(ui_Login_Label1, "User");                                                            // Set label text to "User"
    lv_obj_set_style_text_color(ui_Login_Label1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_Login_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully visible (255)
    lv_obj_set_style_text_font(ui_Login_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create a label for the "Password" text
    ui_Login_Label2 = lv_label_create(ui_Login_Panel2);
    lv_obj_set_width(ui_Login_Label2, LV_SIZE_CONTENT);                                                    // Set width to content size
    lv_obj_set_height(ui_Login_Label2, LV_SIZE_CONTENT);                                                   // Set height to content size
    lv_obj_set_x(ui_Login_Label2, -2);
    lv_obj_set_y(ui_Login_Label2, 8);                                                                  // Set Y position to 10 (below the "User" label)
    lv_obj_set_align(ui_Login_Label2, LV_ALIGN_LEFT_MID);                                                  // Align the label to the left middle of its parent
    lv_label_set_text(ui_Login_Label2, "Password");                                                        // Set label text to "Password"
    lv_obj_set_style_text_color(ui_Login_Label2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_Login_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully visible (255)
    lv_obj_set_style_text_font(ui_Login_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create an input field for the username
    ui_Login_InputUser = lv_textarea_create(ui_Login_Panel2);
    lv_obj_set_width(ui_Login_InputUser, 326);                                                                  // Set width to 326 pixels
    lv_obj_set_height(ui_Login_InputUser, LV_SIZE_CONTENT);                                                     // Set height to content size (about 70 pixels)
    lv_obj_set_x(ui_Login_InputUser, 15);                                                                       // Set X position with some padding (15 pixels)
    lv_obj_set_y(ui_Login_InputUser, -50);                                                                      // Set Y position to -50 (above the password field)
    lv_obj_set_align(ui_Login_InputUser, LV_ALIGN_RIGHT_MID);                                                   // Align the input field to the right middle of its parent
    lv_textarea_set_max_length(ui_Login_InputUser, 20);                                                         // Set the maximum text length to 20 characters
    lv_textarea_set_placeholder_text(ui_Login_InputUser, "Enter username...");                                  // Set placeholder text
    lv_textarea_set_one_line(ui_Login_InputUser, true);                                                         // Set input to single line
    lv_obj_set_style_text_color(ui_Login_InputUser, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set text color to white
    lv_obj_set_style_text_opa(ui_Login_InputUser, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set text opacity to fully visible (255)
    lv_obj_set_style_bg_color(ui_Login_InputUser, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color to dark blue
    lv_obj_set_style_bg_opa(ui_Login_InputUser, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity to fully visible (255)
    lv_obj_set_style_border_color(ui_Login_InputUser, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color to black
    lv_obj_set_style_border_opa(ui_Login_InputUser, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity to 0 (invisible)
    
    lv_obj_set_style_bg_color(ui_Login_InputUser, lv_color_hex(0xAAAAAA), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Login_InputUser, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Login_InputUser, LV_GRAD_DIR_VER, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Create an input field for the password
    ui_Login_InputPass = lv_textarea_create(ui_Login_Panel2);
    lv_obj_set_width(ui_Login_InputPass, 327);                                                                  // Set width to 327 pixels
    lv_obj_set_height(ui_Login_InputPass, LV_SIZE_CONTENT);                                                     // Set height to content size (about 70 pixels)
    lv_obj_set_x(ui_Login_InputPass, 15);                                                                       // Set X position with some padding (15 pixels)
    lv_obj_set_y(ui_Login_InputPass, 50);                                                                       // Set Y position to 50 (below the username field)
    lv_obj_set_align(ui_Login_InputPass, LV_ALIGN_RIGHT_MID);                                                   // Align the input field to the right middle of its parent
    lv_textarea_set_max_length(ui_Login_InputPass, 20);                                                         // Set the maximum text length to 20 characters
    lv_textarea_set_placeholder_text(ui_Login_InputPass, "Enter password...");                                  // Set placeholder text
    lv_textarea_set_one_line(ui_Login_InputPass, true);                                                         // Set input to single line
    lv_textarea_set_password_mode(ui_Login_InputPass, WIFI_INPUT_PWD_FLAG);                                     // Enable password mode (hides characters)
    lv_obj_add_flag(ui_Login_InputPass, LV_OBJ_FLAG_SCROLL_WITH_ARROW);                                         // Enable scrolling with arrow keys
    lv_obj_clear_flag(ui_Login_InputPass, LV_OBJ_FLAG_SCROLL_CHAIN);                                            // Disable scrolling chain
    lv_obj_set_style_text_color(ui_Login_InputPass, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set text color to white
    lv_obj_set_style_text_opa(ui_Login_InputPass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set text opacity to fully visible (255)
    lv_obj_set_style_bg_color(ui_Login_InputPass, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color to dark blue
    lv_obj_set_style_bg_opa(ui_Login_InputPass, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity to fully visible (255)
    lv_obj_set_style_border_color(ui_Login_InputPass, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color to black
    lv_obj_set_style_border_opa(ui_Login_InputPass, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity to 0 (invisible)

    lv_obj_set_style_bg_color(ui_Login_InputPass, lv_color_hex(0xAAAAAA), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Login_InputPass, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Login_InputPass, LV_GRAD_DIR_VER, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Create an eye icon for the password input field to toggle visibility
    ui_Login_InputPass_EYE = lv_img_create(ui_Login_InputPass);
    lv_img_set_src(ui_Login_InputPass_EYE, &ui_img_eye_png);                                  // Set the image source to the eye icon (visibility toggle)
    lv_obj_set_width(ui_Login_InputPass_EYE, LV_SIZE_CONTENT);                                // Set width to content size (34px)
    lv_obj_set_height(ui_Login_InputPass_EYE, LV_SIZE_CONTENT);                               // Set height to content size (20px)
    lv_obj_set_align(ui_Login_InputPass_EYE, LV_ALIGN_RIGHT_MID);                             // Align the eye icon to the right middle of the password input field
    lv_obj_add_flag(ui_Login_InputPass_EYE, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST); // Set flags for clickability and advanced hit test
    lv_obj_clear_flag(ui_Login_InputPass_EYE, LV_OBJ_FLAG_SCROLLABLE);                        // Clear the scrollable flag (eye icon should not scroll)

    // Create a panel for the login failed message
    ui_Login_Panel3 = lv_obj_create(ui_Login_Panel2);
    lv_obj_set_width(ui_Login_Panel3, lv_pct(100));                                                          // Set width to 100% of the parent panel
    lv_obj_set_height(ui_Login_Panel3, lv_pct(60));                                                          // Set height to 60% of the parent panel
    lv_obj_set_align(ui_Login_Panel3, LV_ALIGN_CENTER);                                                      // Align the panel to the center of the parent
    lv_obj_add_flag(ui_Login_Panel3, LV_OBJ_FLAG_HIDDEN);                                                    // Initially hide the panel
    lv_obj_clear_flag(ui_Login_Panel3, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling for this panel
    lv_obj_set_style_bg_color(ui_Login_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color to white
    lv_obj_set_style_bg_opa(ui_Login_Panel3, 200, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity (semi-transparent)
    lv_obj_set_style_border_color(ui_Login_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color to black
    lv_obj_set_style_border_opa(ui_Login_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity to 0 (invisible)

    // Create a label for the login failed message
    ui_Login_Label3 = lv_label_create(ui_Login_Panel3);
    lv_obj_set_width(ui_Login_Label3, lv_pct(100));     // Set width to 100% of the panel
    lv_obj_set_height(ui_Login_Label3, lv_pct(100));    // Set height to 100% of the panel
    lv_obj_set_align(ui_Login_Label3, LV_ALIGN_CENTER); // Align the label to the center of the panel
    lv_label_set_text(ui_Login_Label3,
                      "Login failed\nplease check the username and password\nif not, please create a new one"); // Set error message
    lv_obj_set_style_text_color(ui_Login_Label3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);      // Set text color to red
    lv_obj_set_style_text_opa(ui_Login_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                           // Set text opacity to fully visible (255)
    lv_obj_set_style_text_font(ui_Login_Label3, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);       // Set font to 14px Montserrat

    // Set up the keyboard for username input
    lv_keyboard_set_textarea(ui_Login_Keyboard, ui_Login_InputUser); // Set the keyboard to work with the username input field

    // Add event callbacks for various UI elements
    lv_obj_add_event_cb(ui_Login_Label0, ui_event_Login_Label0, LV_EVENT_ALL, NULL);               // Add event callback for ui_Login_Label0
    lv_obj_add_event_cb(ui_Login_InputUser, ui_event_Login_InputUser, LV_EVENT_ALL, NULL);         // Add event callback for username input
    lv_obj_add_event_cb(ui_Login_InputPass, ui_event_Login_InputPass, LV_EVENT_ALL, NULL);         // Add event callback for password input
    lv_obj_add_event_cb(ui_Login_InputPass_EYE, ui_event_Login_InputPass_EYE, LV_EVENT_ALL, NULL); // Add event callback for eye icon (toggle password visibility)
}
