// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: sq_ui

#include "../ui.h"

// Initialize the main screen for the CAN interface
void ui_Main_CAN_screen_init(void)
{
    // Create the main object for the CAN screen
    ui_Main_CAN = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main_CAN, LV_OBJ_FLAG_SCROLLABLE);                                        // Disable scrolling for this object
    lv_obj_set_style_bg_img_src(ui_Main_CAN, &ui_img_log_on_png, LV_PART_MAIN | LV_STATE_DEFAULT); // Set background image
    // Set the font to a custom font that supports Chinese characters for the main object
    lv_obj_set_style_text_font(ui_Main_CAN, &ui_font_Chinese_Font, LV_STATE_DEFAULT);

    // Create a button on the CAN screen
    ui_CAN_Button1 = lv_btn_create(ui_Main_CAN);
    lv_obj_set_width(ui_CAN_Button1, 400);                                                              // Set the width of the button
    lv_obj_set_height(ui_CAN_Button1, 50);                                                              // Set the height of the button
    lv_obj_set_x(ui_CAN_Button1, 0);                                                                    // Set x position of the button
    lv_obj_set_y(ui_CAN_Button1, 50);                                                                   // Set y position of the button
    lv_obj_set_align(ui_CAN_Button1, LV_ALIGN_CENTER);                                                  // Align the button to the center
    lv_obj_add_flag(ui_CAN_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);                                       // Enable scroll on focus flag
    lv_obj_clear_flag(ui_CAN_Button1, LV_OBJ_FLAG_SCROLLABLE);                                          // Disable scrolling for this button
    lv_obj_set_style_bg_color(ui_CAN_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set button background color to white
    lv_obj_set_style_bg_opa(ui_CAN_Button1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set background opacity to 0 (transparent)

    // Create a label inside the button
    ui_CAN_Label1 = lv_label_create(ui_CAN_Button1);
    lv_obj_set_width(ui_CAN_Label1, LV_SIZE_CONTENT);                                                    // Set label width based on content
    lv_obj_set_height(ui_CAN_Label1, LV_SIZE_CONTENT);                                                   // Set label height based on content
    lv_obj_set_align(ui_CAN_Label1, LV_ALIGN_CENTER);                                                    // Align label to the center of the button
    lv_label_set_text(ui_CAN_Label1, "Click Back");                                                      // Set the text for the label
    lv_obj_set_style_text_color(ui_CAN_Label1, lv_color_hex(0xEE00FF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to gray
    lv_obj_set_style_text_opa(ui_CAN_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully visible
    lv_obj_set_style_text_font(ui_CAN_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create a keyboard for text input on the CAN screen
    ui_CAN_Keyboard0 = lv_keyboard_create(ui_Main_CAN);
    lv_keyboard_set_mode(ui_CAN_Keyboard0, LV_KEYBOARD_MODE_TEXT_UPPER);                                   // Set the keyboard mode to uppercase text
    lv_obj_set_width(ui_CAN_Keyboard0, lv_pct(100));                                                       // Set the keyboard width to 100% of the parent
    lv_obj_set_height(ui_CAN_Keyboard0, lv_pct(50));                                                       // Set the keyboard height to 50% of the parent
    lv_obj_set_align(ui_CAN_Keyboard0, LV_ALIGN_BOTTOM_MID);                                               // Align the keyboard to the bottom middle of the screen
    lv_obj_add_flag(ui_CAN_Keyboard0, LV_OBJ_FLAG_HIDDEN);                                                 // Initially hide the keyboard
    lv_obj_set_style_text_font(ui_CAN_Keyboard0, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT); // Set font for the keyboard
    lv_obj_set_style_bg_opa(ui_CAN_Keyboard0, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                         // Set background opacity to 0 (transparent)

    // Create a container object for the CAN Send interface
    ui_CAN_Send1 = lv_obj_create(ui_Main_CAN);
    lv_obj_set_width(ui_CAN_Send1, lv_pct(50));                                                           // Set the width of the container to 50% of the parent
    lv_obj_set_height(ui_CAN_Send1, lv_pct(50));                                                          // Set the height of the container to 50% of the parent
    lv_obj_set_x(ui_CAN_Send1, -1);                                                                       // Position container with a slight offset on the X-axis
    lv_obj_set_y(ui_CAN_Send1, 0);                                                                        // Position container at the top (Y-axis)
    lv_obj_clear_flag(ui_CAN_Send1, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling for this object
    lv_obj_set_style_bg_color(ui_CAN_Send1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color to white
    lv_obj_set_style_bg_opa(ui_CAN_Send1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set background opacity to 0 (transparent)
    lv_obj_set_style_border_color(ui_CAN_Send1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color to black
    lv_obj_set_style_border_opa(ui_CAN_Send1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity to 0 (invisible)

    // Create a label for the "CAN Send Box" title
    ui_CAN_Send_Box = lv_label_create(ui_CAN_Send1);
    lv_obj_set_width(ui_CAN_Send_Box, LV_SIZE_CONTENT);                                                    // Set label width based on content size
    lv_obj_set_height(ui_CAN_Send_Box, LV_SIZE_CONTENT);  
    lv_obj_set_x(ui_CAN_Send_Box, 0);
    lv_obj_set_y(ui_CAN_Send_Box, -6);                                                 // Set label height based on content size
    lv_label_set_text(ui_CAN_Send_Box, "CAN Send Box");                                                    // Set label text
    lv_obj_set_style_text_color(ui_CAN_Send_Box, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_CAN_Send_Box, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_CAN_Send_Box, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create a textarea for entering the CAN ID
    ui_CAN_Send_ID = lv_textarea_create(ui_CAN_Send1);
    lv_obj_set_width(ui_CAN_Send_ID, lv_pct(48));                                                         // Set textarea width to 48% of the parent
    lv_obj_set_height(ui_CAN_Send_ID, LV_SIZE_CONTENT);                                                   // Set textarea height based on content
    lv_obj_set_x(ui_CAN_Send_ID, 0);                                                                      // Position textarea on the X-axis
    lv_obj_set_y(ui_CAN_Send_ID, 25);                                                                     // Position textarea 25 units from the top
    lv_textarea_set_accepted_chars(ui_CAN_Send_ID, "0123456789AaBbCcDdEeFf ");                            // Accept only valid CAN ID characters
    lv_textarea_set_max_length(ui_CAN_Send_ID, 32);                                                       // Set maximum length of input to 32 characters
    lv_textarea_set_placeholder_text(ui_CAN_Send_ID, "ID...");                                            // Set placeholder text
    lv_textarea_set_one_line(ui_CAN_Send_ID, true);                                                       // Make the textarea a single line
    lv_obj_set_style_text_color(ui_CAN_Send_ID, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_CAN_Send_ID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully visible
    lv_obj_set_style_bg_color(ui_CAN_Send_ID, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set background color to white
    lv_obj_set_style_bg_opa(ui_CAN_Send_ID, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity to 0 (transparent)

    lv_obj_set_style_radius(ui_CAN_Send_ID, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CAN_Send_ID, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CAN_Send_ID, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Create a textarea for entering the CAN length
    ui_CAN_Send_Len = lv_textarea_create(ui_CAN_Send1);
    lv_obj_set_width(ui_CAN_Send_Len, lv_pct(48));                                                         // Set textarea width to 48% of the parent
    lv_obj_set_height(ui_CAN_Send_Len, LV_SIZE_CONTENT);                                                   // Set textarea height based on content
    lv_obj_set_x(ui_CAN_Send_Len, 0);                                                                      // Position textarea on the X-axis
    lv_obj_set_y(ui_CAN_Send_Len, 25);                                                                     // Position textarea 25 units from the top
    lv_obj_set_align(ui_CAN_Send_Len, LV_ALIGN_TOP_RIGHT);                                                 // Align textarea to the top-right corner
    lv_textarea_set_accepted_chars(ui_CAN_Send_Len, "012345678");                                          // Accept only valid length characters
    lv_textarea_set_placeholder_text(ui_CAN_Send_Len, "Length...");                                        // Set placeholder text
    lv_textarea_set_one_line(ui_CAN_Send_Len, true);                                                       // Make the textarea a single line
    lv_obj_set_style_text_color(ui_CAN_Send_Len, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_CAN_Send_Len, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully visible
    lv_obj_set_style_bg_color(ui_CAN_Send_Len, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set background color to white
    lv_obj_set_style_bg_opa(ui_CAN_Send_Len, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity to 0 (transparent)
    
    lv_obj_set_style_radius(ui_CAN_Send_Len, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CAN_Send_Len, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CAN_Send_Len, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);

    // Create a textarea for entering the CAN data
    ui_CAN_Send_Data = lv_textarea_create(ui_CAN_Send1);
    lv_obj_set_width(ui_CAN_Send_Data, lv_pct(100));                                                        // Set textarea width to 100% of the parent
    lv_obj_set_height(ui_CAN_Send_Data, lv_pct(60));                                                        // Set textarea height to 60% of the parent
    lv_obj_set_align(ui_CAN_Send_Data, LV_ALIGN_BOTTOM_MID);                                                // Align textarea to the bottom center
    lv_textarea_set_accepted_chars(ui_CAN_Send_Data, "0123456789AaBbCcDdEeFf ");                            // Accept only valid data characters
    lv_textarea_set_max_length(ui_CAN_Send_Data, 1024);                                                     // Set maximum length of input to 1024 characters
    lv_textarea_set_placeholder_text(ui_CAN_Send_Data, "Data(Hex)...");                                     // Set placeholder text
    lv_obj_set_style_text_color(ui_CAN_Send_Data, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_CAN_Send_Data, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully visible
    lv_obj_set_style_bg_color(ui_CAN_Send_Data, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set background color to white
    lv_obj_set_style_bg_opa(ui_CAN_Send_Data, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity to 0 (transparent)

    lv_obj_set_style_radius(ui_CAN_Send_Data, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CAN_Send_Data, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CAN_Send_Data, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);


    // Create a button (Button 2) for "Baud rate" option in the CAN send section
    ui_CAN_Button2 = lv_btn_create(ui_CAN_Send1);
    lv_obj_set_width(ui_CAN_Button2, 130);                                                              // Set width of the button
    lv_obj_set_height(ui_CAN_Button2, 35);                                                              // Set height of the button
    lv_obj_set_x(ui_CAN_Button2, 0);                                                                    // Set horizontal position
    lv_obj_set_y(ui_CAN_Button2, -15);                                                                  // Set vertical position
    lv_obj_set_align(ui_CAN_Button2, LV_ALIGN_TOP_RIGHT);                                               // Align to top-right corner
    lv_obj_add_flag(ui_CAN_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);                                       // Enable scroll on focus
    lv_obj_clear_flag(ui_CAN_Button2, LV_OBJ_FLAG_SCROLLABLE);                                          // Disable scrolling on the button
    lv_obj_set_style_bg_color(ui_CAN_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set button background color
    lv_obj_set_style_bg_opa(ui_CAN_Button2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set background opacity

    // Create a label for Button 2 with the text "Baud rate"
    ui_CAN_Label2 = lv_label_create(ui_CAN_Button2);
    lv_obj_set_width(ui_CAN_Label2, LV_SIZE_CONTENT);                                                    // Set width to fit content
    lv_obj_set_height(ui_CAN_Label2, LV_SIZE_CONTENT);                                                   // Set height to fit content
    lv_obj_set_align(ui_CAN_Label2, LV_ALIGN_CENTER);                                                    // Align label text to center
    lv_label_set_text(ui_CAN_Label2, "Baud rate");                                                       // Set text for the label
    lv_obj_set_style_text_color(ui_CAN_Label2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set label text color
    lv_obj_set_style_text_opa(ui_CAN_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_CAN_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create a button (Button 3) for "Save" option in the CAN send section
    ui_CAN_Button3 = lv_btn_create(ui_CAN_Send1);
    lv_obj_set_width(ui_CAN_Button3, 80);                                                               // Set width of the button
    lv_obj_set_height(ui_CAN_Button3, 35);                                                              // Set height of the button
    lv_obj_set_x(ui_CAN_Button3, -140);                                                                 // Set horizontal position
    lv_obj_set_y(ui_CAN_Button3, -15);                                                                  // Set vertical position
    lv_obj_set_align(ui_CAN_Button3, LV_ALIGN_TOP_RIGHT);                                               // Align to top-right corner
    lv_obj_add_flag(ui_CAN_Button3, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);                  // Make the button hidden initially and enable scroll on focus
    lv_obj_clear_flag(ui_CAN_Button3, LV_OBJ_FLAG_SCROLLABLE);                                          // Disable scrolling on the button
    lv_obj_set_style_bg_color(ui_CAN_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set button background color
    lv_obj_set_style_bg_opa(ui_CAN_Button3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set background opacity

    // Create a label for Button 3 with the text "Save"
    ui_CAN_Label3 = lv_label_create(ui_CAN_Button3);
    lv_obj_set_width(ui_CAN_Label3, LV_SIZE_CONTENT);                                                    // Set width to fit content
    lv_obj_set_height(ui_CAN_Label3, LV_SIZE_CONTENT);                                                   // Set height to fit content
    lv_obj_set_align(ui_CAN_Label3, LV_ALIGN_CENTER);                                                    // Align label text to center
    lv_label_set_text(ui_CAN_Label3, "Save");                                                            // Set text for the label
    lv_obj_set_style_text_color(ui_CAN_Label3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set label text color
    lv_obj_set_style_text_opa(ui_CAN_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_CAN_Label3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create a new object for CAN read section (Read1)
    ui_CAN_Read1 = lv_obj_create(ui_Main_CAN);
    lv_obj_set_width(ui_CAN_Read1, lv_pct(50));                                                           // Set width to 50% of parent object
    lv_obj_set_height(ui_CAN_Read1, lv_pct(50));                                                          // Set height to 50% of parent object
    lv_obj_set_align(ui_CAN_Read1, LV_ALIGN_TOP_RIGHT);                                                   // Align to top-right corner
    lv_obj_clear_flag(ui_CAN_Read1, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling on the container
    lv_obj_set_style_bg_color(ui_CAN_Read1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color
    lv_obj_set_style_bg_opa(ui_CAN_Read1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set background opacity
    lv_obj_set_style_border_color(ui_CAN_Read1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color
    lv_obj_set_style_border_opa(ui_CAN_Read1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity

    // Create a text area inside the CAN read section for displaying read data
    ui_CAN_Read_Area = lv_textarea_create(ui_CAN_Read1);
    lv_obj_set_width(ui_CAN_Read_Area, lv_pct(100));                                                        // Set width to 100% of parent object
    lv_obj_set_height(ui_CAN_Read_Area, lv_pct(80));                                                        // Set height to 80% of parent object
    lv_obj_set_align(ui_CAN_Read_Area, LV_ALIGN_BOTTOM_MID);                                                // Align to bottom-center
    lv_textarea_set_placeholder_text(ui_CAN_Read_Area, "Read...");                                          // Set placeholder text
    lv_obj_set_style_text_color(ui_CAN_Read_Area, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(ui_CAN_Read_Area, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_bg_color(ui_CAN_Read_Area, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set background color
    lv_obj_set_style_bg_opa(ui_CAN_Read_Area, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity

    // Create a label for the "CAN Read Box"
    ui_CAN_Read_Box = lv_label_create(ui_CAN_Read1);
    lv_obj_set_width(ui_CAN_Read_Box, LV_SIZE_CONTENT);                                                    // Set width to fit content
    lv_obj_set_height(ui_CAN_Read_Box, LV_SIZE_CONTENT);                                                   // Set height to fit content
    lv_label_set_text(ui_CAN_Read_Box, "CAN Read Box");                                                    // Set label text
    lv_obj_set_style_text_color(ui_CAN_Read_Box, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(ui_CAN_Read_Box, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_CAN_Read_Box, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create a button (Button 4) for "Clear" functionality in the CAN read section
    ui_CAN_Button4 = lv_btn_create(ui_CAN_Read1);
    lv_obj_set_width(ui_CAN_Button4, 80);                                                               // Set width of the button
    lv_obj_set_height(ui_CAN_Button4, 35);                                                              // Set height of the button
    lv_obj_set_x(ui_CAN_Button4, 0);                                                                    // Set horizontal position
    lv_obj_set_y(ui_CAN_Button4, -15);                                                                  // Set vertical position
    lv_obj_set_align(ui_CAN_Button4, LV_ALIGN_TOP_RIGHT);                                               // Align to top-right corner
    lv_obj_add_flag(ui_CAN_Button4, LV_OBJ_FLAG_SCROLL_ON_FOCUS);                                       // Enable scroll on focus
    lv_obj_clear_flag(ui_CAN_Button4, LV_OBJ_FLAG_SCROLLABLE);                                          // Disable scrolling on the button
    lv_obj_set_style_bg_color(ui_CAN_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set button background color
    lv_obj_set_style_bg_opa(ui_CAN_Button4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set background opacity

    // Create a label for Button 4 with the text "Clear"
    ui_CAN_Label4 = lv_label_create(ui_CAN_Button4);
    lv_obj_set_width(ui_CAN_Label4, LV_SIZE_CONTENT);                                                    // Set width to fit content
    lv_obj_set_height(ui_CAN_Label4, LV_SIZE_CONTENT);                                                   // Set height to fit content
    lv_obj_set_align(ui_CAN_Label4, LV_ALIGN_CENTER);                                                    // Align label text to center
    lv_label_set_text(ui_CAN_Label4, "Clear");                                                           // Set text for the label
    lv_obj_set_style_text_color(ui_CAN_Label4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set label text color
    lv_obj_set_style_text_opa(ui_CAN_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_CAN_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create a roller for selecting CAN baud rates
    ui_CAN_Roller = lv_roller_create(ui_Main_CAN);
    lv_roller_set_options(ui_CAN_Roller, "25K\n50K\n100K\n125K\n250K\n500K\n800K\n1M", LV_ROLLER_MODE_INFINITE); // Set roller options for baud rates
    lv_roller_set_selected(ui_CAN_Roller, 5, LV_ANIM_OFF);                                                       // Select the 6th option (500K) initially, no animation
    lv_obj_set_height(ui_CAN_Roller, 230);                                                                       // Set height of the roller
    lv_obj_set_width(ui_CAN_Roller, LV_SIZE_CONTENT);                                                            // Set width to fit content
    lv_obj_set_align(ui_CAN_Roller, LV_ALIGN_CENTER);                                                            // Align roller to the center
    lv_obj_add_flag(ui_CAN_Roller, LV_OBJ_FLAG_HIDDEN);                                                          // Make the roller hidden initially
    lv_obj_set_style_text_color(ui_CAN_Roller, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);         // Set text color
    lv_obj_set_style_text_opa(ui_CAN_Roller, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                              // Set text opacity
    lv_obj_set_style_text_font(ui_CAN_Roller, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_CAN_Roller, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);           // Set background color
    lv_obj_set_style_bg_opa(ui_CAN_Roller, 100, LV_PART_MAIN | LV_STATE_DEFAULT);                                  // Set background opacity
    lv_obj_set_style_text_font(ui_CAN_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Add event handlers for various UI elements
    lv_obj_add_event_cb(ui_CAN_Button1, ui_event_CAN_Button1, LV_EVENT_ALL, NULL);     // Add event callback for Button 1
    lv_keyboard_set_textarea(ui_CAN_Keyboard0, ui_RS485_Read_Area);                    // Link keyboard to text area
    lv_obj_add_event_cb(ui_CAN_Send_ID, ui_event_CAN_Send_ID, LV_EVENT_ALL, NULL);     // Add event callback for Send ID button
    lv_obj_add_event_cb(ui_CAN_Send_Len, ui_event_CAN_Send_Len, LV_EVENT_ALL, NULL);   // Add event callback for Send Length button
    lv_obj_add_event_cb(ui_CAN_Send_Data, ui_event_CAN_Send_Data, LV_EVENT_ALL, NULL); // Add event callback for Send Data button
    lv_obj_add_event_cb(ui_CAN_Button2, ui_event_CAN_Button2, LV_EVENT_ALL, NULL);     // Add event callback for Button 2
    lv_obj_add_event_cb(ui_CAN_Button3, ui_event_CAN_Button3, LV_EVENT_ALL, NULL);     // Add event callback for Button 3
    lv_obj_add_event_cb(ui_CAN_Button4, ui_event_CAN_Button4, LV_EVENT_ALL, NULL);     // Add event callback for Button 4
}