// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: sq_ui

#include "../ui.h"

// Function to initialize the main screen
void ui_Main_screen_init(void)
{
    // Create the main screen object
    ui_Main = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main, LV_OBJ_FLAG_SCROLLABLE);                                        // Disable scrolling on the main screen
    lv_obj_set_style_bg_img_src(ui_Main, &ui_img_log_on_png, LV_PART_MAIN | LV_STATE_DEFAULT); // Set background image for main screen

    // Create the WiFi object inside the main screen
    ui_Wifi = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_Wifi, lv_pct(50));                                                           // Set WiFi object width to 50% of the screen
    lv_obj_set_height(ui_Wifi, lv_pct(50));                                                          // Set WiFi object height to 50% of the screen
    lv_obj_clear_flag(ui_Wifi, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling for WiFi object
    lv_obj_set_style_bg_color(ui_Wifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Wifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Wifi, &ui_img_wifi_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_Wifi, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Wifi, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Wifi, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create the RS485 object inside the main screen
    ui_RS485 = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_RS485, lv_pct(50));                                                           // Set RS485 object width to 50% of the screen
    lv_obj_set_height(ui_RS485, lv_pct(50));                                                          // Set RS485 object height to 50% of the screen
    lv_obj_set_align(ui_RS485, LV_ALIGN_TOP_RIGHT);                                                   // Align RS485 object to the top-right of the screen
    lv_obj_clear_flag(ui_RS485, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling for RS485 object
    lv_obj_set_style_bg_color(ui_RS485, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RS485, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_RS485, &ui_img_485_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_RS485, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RS485, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RS485, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create the CAN object inside the main screen
    ui_CAN = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_CAN, lv_pct(50));                                                           // Set CAN object width to 50% of the screen
    lv_obj_set_height(ui_CAN, lv_pct(50));                                                          // Set CAN object height to 50% of the screen
    lv_obj_set_align(ui_CAN, LV_ALIGN_BOTTOM_RIGHT);                                                // Align CAN object to the bottom-right of the screen
    lv_obj_clear_flag(ui_CAN, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling for CAN object
    lv_obj_set_style_bg_color(ui_CAN, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_CAN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_CAN, &ui_img_can_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_CAN, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_CAN, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_CAN, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create the PWM object inside the main screen
    ui_PWM = lv_obj_create(ui_Main);
    lv_obj_set_width(ui_PWM, lv_pct(50));                                                           // Set PWM object width to 50% of the screen
    lv_obj_set_height(ui_PWM, lv_pct(50));                                                          // Set PWM object height to 50% of the screen
    lv_obj_set_align(ui_PWM, LV_ALIGN_BOTTOM_LEFT);                                                 // Align PWM object to the bottom-left of the screen
    lv_obj_clear_flag(ui_PWM, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling for PWM object
    lv_obj_set_style_bg_color(ui_PWM, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PWM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_PWM, &ui_img_pwm_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_opa(ui_PWM, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_PWM, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_PWM, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Add event callbacks for each UI object
    lv_obj_add_event_cb(ui_Wifi, ui_event_Wifi, LV_EVENT_ALL, NULL);   // Add event callback for the WiFi object
    lv_obj_add_event_cb(ui_RS485, ui_event_RS485, LV_EVENT_ALL, NULL); // Add event callback for the RS485 object
    lv_obj_add_event_cb(ui_CAN, ui_event_CAN, LV_EVENT_ALL, NULL);     // Add event callback for the CAN object
    lv_obj_add_event_cb(ui_PWM, ui_event_PWM, LV_EVENT_ALL, NULL);     // Add event callback for the PWM object
}
