// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: sq_ui

#include "../ui.h"

// Initialize the main PWM screen
void ui_Main_PWM_screen_init(void)
{
    // Create the main screen object for PWM
    ui_Main_PWM = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main_PWM, LV_OBJ_FLAG_SCROLLABLE);                                        // Disable scrolling on the main screen
    lv_obj_set_style_bg_img_src(ui_Main_PWM, &ui_img_log_on_png, LV_PART_MAIN | LV_STATE_DEFAULT); // Set background image for the screen
    // Set the font to support Chinese characters using a custom font
    lv_obj_set_style_text_font(ui_Main_PWM, &ui_font_Chinese_Font, LV_STATE_DEFAULT);

    // Create a panel for displaying the arc control (PWM value display)
    ui_PWM_Panel1 = lv_obj_create(ui_Main_PWM);
    lv_obj_set_width(ui_PWM_Panel1, lv_pct(50));                                                           // Set the width to 50% of the parent container
    lv_obj_set_height(ui_PWM_Panel1, lv_pct(50));                                                          // Set the height to 50% of the parent container
    lv_obj_clear_flag(ui_PWM_Panel1, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling on this panel
    lv_obj_set_style_bg_color(ui_PWM_Panel1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color
    lv_obj_set_style_bg_opa(ui_PWM_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set background opacity to 0 (transparent)
    lv_obj_set_style_border_color(ui_PWM_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color
    lv_obj_set_style_border_opa(ui_PWM_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity to 0

    // Create an arc to represent the PWM value (50% initially)
    ui_PWM_Arc0 = lv_arc_create(ui_PWM_Panel1);
    lv_obj_set_width(ui_PWM_Arc0, 200);                                                               // Set width of the arc
    lv_obj_set_height(ui_PWM_Arc0, 200);                                                              // Set height of the arc
    lv_obj_set_align(ui_PWM_Arc0, LV_ALIGN_CENTER);                                                   // Align the arc to the center of the panel
    lv_arc_set_value(ui_PWM_Arc0, 50);                                                                // Set the initial value of the arc to 50%
    lv_obj_set_style_arc_color(ui_PWM_Arc0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set arc color to white
    lv_obj_set_style_arc_opa(ui_PWM_Arc0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set arc opacity to full

    lv_obj_set_style_arc_color(ui_PWM_Arc0, lv_color_hex(0xBBE1F2), LV_PART_INDICATOR | LV_STATE_DEFAULT); // Set arc indicator color
    lv_obj_set_style_arc_opa(ui_PWM_Arc0, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);                      // Set indicator opacity to full

    lv_obj_set_style_bg_color(ui_PWM_Arc0, lv_color_hex(0xBBE1F2), LV_PART_KNOB | LV_STATE_DEFAULT); // Set knob background color
    lv_obj_set_style_bg_opa(ui_PWM_Arc0, 255, LV_PART_KNOB | LV_STATE_DEFAULT);                      // Set knob background opacity to full

    // Create a label to display the PWM value on the arc
    ui_PWM_Label0 = lv_label_create(ui_PWM_Panel1);
    lv_obj_set_width(ui_PWM_Label0, LV_SIZE_CONTENT);                                                    // Set label width based on content
    lv_obj_set_height(ui_PWM_Label0, LV_SIZE_CONTENT);                                                   // Set label height based on content
    lv_obj_set_align(ui_PWM_Label0, LV_ALIGN_CENTER);                                                    // Align label to the center of the arc
    lv_label_set_text(ui_PWM_Label0, "50");                                                              // Set the initial text of the label to "50"
    lv_obj_set_style_text_color(ui_PWM_Label0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_PWM_Label0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to full
    lv_obj_set_style_text_font(ui_PWM_Label0, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWM_Label9 = lv_label_create(ui_PWM_Panel1);
    lv_obj_set_width(ui_PWM_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PWM_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PWM_Label9, 0);
    lv_obj_set_y(ui_PWM_Label9, -10);
    lv_obj_set_align(ui_PWM_Label9, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_PWM_Label9, "Sliding to change brightness");
    lv_obj_set_style_text_color(ui_PWM_Label9, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PWM_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PWM_Label9, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create a second panel for the PWM slider (to control PWM value)
    ui_PWM_Panel2 = lv_obj_create(ui_Main_PWM);
    lv_obj_set_width(ui_PWM_Panel2, lv_pct(50));                                                           // Set the width to 50% of the parent container
    lv_obj_set_height(ui_PWM_Panel2, lv_pct(50));                                                          // Set the height to 50% of the parent container
    lv_obj_set_align(ui_PWM_Panel2, LV_ALIGN_TOP_RIGHT);                                                   // Align the panel to the top-right of the screen
    lv_obj_clear_flag(ui_PWM_Panel2, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling on this panel
    lv_obj_set_style_bg_color(ui_PWM_Panel2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color
    lv_obj_set_style_bg_opa(ui_PWM_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set background opacity to 0 (transparent)
    lv_obj_set_style_border_color(ui_PWM_Panel2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color
    lv_obj_set_style_border_opa(ui_PWM_Panel2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity to 0

    // Create a slider to control the PWM value
    ui_PWM_Slider0 = lv_slider_create(ui_PWM_Panel2);
    lv_slider_set_value(ui_PWM_Slider0, 50, LV_ANIM_OFF); // Set initial value of the slider to 0 without animation
    if (lv_slider_get_mode(ui_PWM_Slider0) == LV_SLIDER_MODE_RANGE)
        lv_slider_set_left_value(ui_PWM_Slider0, 50, LV_ANIM_OFF); // Set the left value of the slider (if range mode)
    lv_obj_set_width(ui_PWM_Slider0, lv_pct(80));                 // Set width to 80% of the panel
    lv_obj_set_height(ui_PWM_Slider0, lv_pct(10));                // Set height to 10% of the panel
    lv_obj_set_align(ui_PWM_Slider0, LV_ALIGN_CENTER);            // Align the slider to the center of the panel

    // Style the slider's indicator
    lv_obj_set_style_bg_color(ui_PWM_Slider0, lv_color_hex(0x000000), LV_PART_INDICATOR | LV_STATE_DEFAULT);      // Set indicator color to black
    lv_obj_set_style_bg_opa(ui_PWM_Slider0, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);                           // Set indicator opacity to full
    lv_obj_set_style_bg_grad_color(ui_PWM_Slider0, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_DEFAULT); // Set gradient color for the indicator
    lv_obj_set_style_bg_grad_dir(ui_PWM_Slider0, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);          // Set horizontal gradient direction

    // Style the slider's knob
    lv_obj_set_style_bg_color(ui_PWM_Slider0, lv_color_hex(0x000000), LV_PART_KNOB | LV_STATE_DEFAULT);      // Set knob color to black
    lv_obj_set_style_bg_opa(ui_PWM_Slider0, 255, LV_PART_KNOB | LV_STATE_DEFAULT);                           // Set knob opacity to full
    lv_obj_set_style_bg_grad_color(ui_PWM_Slider0, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT); // Set gradient color for the knob
    lv_obj_set_style_bg_grad_dir(ui_PWM_Slider0, LV_GRAD_DIR_HOR, LV_PART_KNOB | LV_STATE_DEFAULT);          // Set horizontal gradient direction

    // Create a label to display the value of the slider
    ui_PWM_Label1 = lv_label_create(ui_PWM_Panel2);
    lv_obj_set_width(ui_PWM_Label1, LV_SIZE_CONTENT);                                                    // Set label width based on content
    lv_obj_set_height(ui_PWM_Label1, LV_SIZE_CONTENT);                                                   // Set label height based on content
    lv_obj_set_x(ui_PWM_Label1, 0);                                                                      // Set x position to 0 (relative to parent container)
    lv_obj_set_y(ui_PWM_Label1, 50);                                                                     // Set y position to 50 (relative to parent container)
    lv_obj_set_align(ui_PWM_Label1, LV_ALIGN_TOP_MID);                                                   // Align label to the top-middle of the panel
    lv_label_set_text(ui_PWM_Label1, "50");                                                               // Set the initial text to "0"
    lv_obj_set_style_text_color(ui_PWM_Label1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_PWM_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to full
    lv_obj_set_style_text_font(ui_PWM_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    ui_BAT_Label0 = lv_label_create(ui_PWM_Panel2);
    lv_obj_set_width(ui_BAT_Label0, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BAT_Label0, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BAT_Label0, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_BAT_Label0, "BAT:3.7V");
    lv_obj_set_style_text_color(ui_BAT_Label0, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_BAT_Label0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_BAT_Label0, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create a new panel for PWM switch controls
    ui_PWM_Panel3 = lv_obj_create(ui_Main_PWM);
    lv_obj_set_width(ui_PWM_Panel3, lv_pct(50));                                                           // Set width to 50% of the parent container
    lv_obj_set_height(ui_PWM_Panel3, lv_pct(50));                                                          // Set height to 50% of the parent container
    lv_obj_set_align(ui_PWM_Panel3, LV_ALIGN_BOTTOM_LEFT);                                                 // Align the panel to the bottom-left corner
    lv_obj_clear_flag(ui_PWM_Panel3, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling for the panel
    lv_obj_set_style_bg_color(ui_PWM_Panel3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color to white
    lv_obj_set_style_bg_opa(ui_PWM_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set background opacity to 0 (transparent)
    lv_obj_set_style_border_color(ui_PWM_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color to black
    lv_obj_set_style_border_opa(ui_PWM_Panel3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity to 0 (transparent)

    // Create the first PWM switch (orange color)
    ui_PWM_Switch1 = lv_switch_create(ui_PWM_Panel3);
    lv_obj_set_width(ui_PWM_Switch1, 60);                                                                         // Set width to 60
    lv_obj_set_height(ui_PWM_Switch1, 30);                                                                        // Set height to 30
    lv_obj_set_x(ui_PWM_Switch1, -30);                                                                            // Set horizontal position to -30
    lv_obj_set_y(ui_PWM_Switch1, 0);                                                                              // Set vertical position to 0
    lv_obj_set_align(ui_PWM_Switch1, LV_ALIGN_TOP_MID);                                                           // Align the switch to the top-center of the panel
    lv_obj_set_style_bg_color(ui_PWM_Switch1, lv_color_hex(0xFFA500), LV_PART_INDICATOR | LV_STATE_DEFAULT);      // Set background color to orange
    lv_obj_set_style_bg_opa(ui_PWM_Switch1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);                           // Set opacity to fully opaque
    lv_obj_set_style_bg_grad_color(ui_PWM_Switch1, lv_color_hex(0xFF1493), LV_PART_INDICATOR | LV_STATE_DEFAULT); // Set gradient color to deep pink
    lv_obj_set_style_bg_grad_dir(ui_PWM_Switch1, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);          // Set horizontal gradient direction

    // Create the second PWM switch (green color)
    ui_PWM_Switch2 = lv_switch_create(ui_PWM_Panel3);
    lv_obj_set_width(ui_PWM_Switch2, 60);                                                                         // Set width to 60
    lv_obj_set_height(ui_PWM_Switch2, 30);                                                                        // Set height to 30
    lv_obj_set_x(ui_PWM_Switch2, -30);                                                                            // Set horizontal position to -30
    lv_obj_set_y(ui_PWM_Switch2, 0);                                                                              // Set vertical position to 0
    lv_obj_set_align(ui_PWM_Switch2, LV_ALIGN_CENTER);                                                            // Align the switch to the center of the panel
    lv_obj_set_style_bg_color(ui_PWM_Switch2, lv_color_hex(0x00FF00), LV_PART_INDICATOR | LV_STATE_DEFAULT);      // Set background color to green
    lv_obj_set_style_bg_opa(ui_PWM_Switch2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);                           // Set opacity to fully opaque
    lv_obj_set_style_bg_grad_color(ui_PWM_Switch2, lv_color_hex(0xFFFF00), LV_PART_INDICATOR | LV_STATE_DEFAULT); // Set gradient color to yellow
    lv_obj_set_style_bg_grad_dir(ui_PWM_Switch2, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);          // Set horizontal gradient direction

    // Create the third PWM switch (blue color)
    ui_PWM_Switch3 = lv_switch_create(ui_PWM_Panel3);
    lv_obj_set_width(ui_PWM_Switch3, 60);                                                                         // Set width to 60
    lv_obj_set_height(ui_PWM_Switch3, 30);                                                                        // Set height to 30
    lv_obj_set_x(ui_PWM_Switch3, -30);                                                                            // Set horizontal position to -30
    lv_obj_set_y(ui_PWM_Switch3, 0);                                                                              // Set vertical position to 0
    lv_obj_set_align(ui_PWM_Switch3, LV_ALIGN_BOTTOM_MID);                                                        // Align the switch to the bottom-center of the panel
    lv_obj_set_style_bg_color(ui_PWM_Switch3, lv_color_hex(0x00A1FF), LV_PART_INDICATOR | LV_STATE_DEFAULT);      // Set background color to blue
    lv_obj_set_style_bg_opa(ui_PWM_Switch3, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);                           // Set opacity to fully opaque
    lv_obj_set_style_bg_grad_color(ui_PWM_Switch3, lv_color_hex(0x9B00FF), LV_PART_INDICATOR | LV_STATE_DEFAULT); // Set gradient color to purple
    lv_obj_set_style_bg_grad_dir(ui_PWM_Switch3, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);          // Set horizontal gradient direction

    // Create a label for the first switch (33% text)
    ui_PWM_Label2 = lv_label_create(ui_PWM_Panel3);
    lv_obj_set_width(ui_PWM_Label2, LV_SIZE_CONTENT);                                                    // Set label width to content size
    lv_obj_set_height(ui_PWM_Label2, LV_SIZE_CONTENT);                                                   // Set label height to content size
    lv_obj_set_x(ui_PWM_Label2, 35);                                                                     // Set x position to 30
    lv_obj_set_y(ui_PWM_Label2, 5);                                                                      // Set y position to 5
    lv_obj_set_align(ui_PWM_Label2, LV_ALIGN_TOP_MID);                                                   // Align label to the top-center of the panel
    lv_label_set_text(ui_PWM_Label2, "33%");                                                             // Set the label text to "33%"
    lv_obj_set_style_text_color(ui_PWM_Label2, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_PWM_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully opaque
    lv_obj_set_style_bg_grad_dir(ui_PWM_Label2, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);       // Set gradient direction to horizontal
    lv_obj_set_style_text_font(ui_PWM_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Create a label for the second switch (66% text)
    ui_PWM_Label3 = lv_label_create(ui_PWM_Panel3);
    lv_obj_set_width(ui_PWM_Label3, LV_SIZE_CONTENT);                                                    // Set label width to content size
    lv_obj_set_height(ui_PWM_Label3, LV_SIZE_CONTENT);                                                   // Set label height to content size
    lv_obj_set_x(ui_PWM_Label3, 35);                                                                     // Set x position to 35
    lv_obj_set_y(ui_PWM_Label3, 0);                                                                      // Set y position to 0
    lv_obj_set_align(ui_PWM_Label3, LV_ALIGN_CENTER);                                                    // Align label to the center of the panel
    lv_label_set_text(ui_PWM_Label3, "66%");                                                             // Set the label text to "66%"
    lv_obj_set_style_text_color(ui_PWM_Label3, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_PWM_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully opaque
    lv_obj_set_style_text_font(ui_PWM_Label3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWM_Label4 = lv_label_create(ui_PWM_Panel3);                                                      // Create label 4
    lv_obj_set_width(ui_PWM_Label4, LV_SIZE_CONTENT);                                                    /// Set width based on content
    lv_obj_set_height(ui_PWM_Label4, LV_SIZE_CONTENT);                                                   /// Set height based on content
    lv_obj_set_x(ui_PWM_Label4, 35);                                                                     // Set X position
    lv_obj_set_y(ui_PWM_Label4, -5);                                                                     // Set Y position
    lv_obj_set_align(ui_PWM_Label4, LV_ALIGN_BOTTOM_MID);                                                // Align at the bottom middle
    lv_label_set_text(ui_PWM_Label4, "99%");                                                             // Set text
    lv_obj_set_style_text_color(ui_PWM_Label4, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(ui_PWM_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_PWM_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWM_Panel4 = lv_obj_create(ui_Main_PWM);                                                            // Create panel 4
    lv_obj_set_width(ui_PWM_Panel4, lv_pct(50));                                                           // Set width to 50% of parent
    lv_obj_set_height(ui_PWM_Panel4, lv_pct(60));                                                          // Set height to 60% of parent
    lv_obj_set_align(ui_PWM_Panel4, LV_ALIGN_BOTTOM_RIGHT);                                                // Align to the bottom right
    lv_obj_clear_flag(ui_PWM_Panel4, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling
    lv_obj_set_style_bg_color(ui_PWM_Panel4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color
    lv_obj_set_style_bg_opa(ui_PWM_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set background opacity
    lv_obj_set_style_border_color(ui_PWM_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color
    lv_obj_set_style_border_opa(ui_PWM_Panel4, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity

    ui_PWM_Label5 = lv_label_create(ui_PWM_Panel4);                                                      // Create label 5
    lv_obj_set_width(ui_PWM_Label5, lv_pct(100));                                                        // Set width to 100% of parent
    lv_obj_set_height(ui_PWM_Label5, lv_pct(20));                                                        // Set height to 10% of parent
    lv_obj_set_x(ui_PWM_Label5, 0);
    lv_obj_set_y(ui_PWM_Label5, -10);
    lv_obj_set_align(ui_PWM_Label5, LV_ALIGN_TOP_MID);                                                   // Align at the top middle
    lv_label_set_text(ui_PWM_Label5, "Micro SD Info:\n");                                                     // Set tutorial text
    lv_obj_set_style_text_color(ui_PWM_Label5, lv_color_hex(0xFFC0CB), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(ui_PWM_Label5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_PWM_Label5, &lv_font_montserrat_44, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWM_Label6 = lv_label_create(ui_PWM_Panel4);
    lv_obj_set_width(ui_PWM_Label6, lv_pct(100));
    lv_obj_set_height(ui_PWM_Label6, lv_pct(60));
    lv_obj_set_x(ui_PWM_Label6, 0);
    lv_obj_set_y(ui_PWM_Label6, -10);
    lv_obj_set_align(ui_PWM_Label6, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_PWM_Label6, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_label_set_text(ui_PWM_Label6,
                      "Name: SD64G\nType: SDHC/SDXC\nSpeed: 40.00 MHz (limit: 40.00 MHz)\nSize: 60906MB\nCSD: ver=2, sector_size=512, capacity=124735488 read_bl_len=9\nSSR: bus_width=1");
    lv_obj_set_style_text_color(ui_PWM_Label6, lv_color_hex(0x00FFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_PWM_Label6, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_PWM_Label6, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PWM_Button0 = lv_btn_create(ui_PWM_Panel4);                                                      // Create button 0
    lv_obj_set_width(ui_PWM_Button0, 175);                                                              // Set width to 100
    lv_obj_set_height(ui_PWM_Button0, 50);                                                              // Set height to 50
    lv_obj_set_x(ui_PWM_Button0, 0);                                                                    // Set X position
    lv_obj_set_y(ui_PWM_Button0, 90);                                                                   // Set Y position
    lv_obj_set_align(ui_PWM_Button0, LV_ALIGN_CENTER);                                                  // Align at the center
    lv_obj_add_flag(ui_PWM_Button0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);                                       // Enable scrolling on focus
    lv_obj_clear_flag(ui_PWM_Button0, LV_OBJ_FLAG_SCROLLABLE);                                          // Disable scrolling
    lv_obj_set_style_bg_color(ui_PWM_Button0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set background color
    lv_obj_set_style_bg_opa(ui_PWM_Button0, 100, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set background opacity

    ui_PWM_Label8 = lv_label_create(ui_PWM_Button0);                                                     // Create label for button 0
    lv_obj_set_width(ui_PWM_Label8, LV_SIZE_CONTENT);                                                    /// Set width based on content
    lv_obj_set_height(ui_PWM_Label8, LV_SIZE_CONTENT);                                                   /// Set height based on content
    lv_obj_set_align(ui_PWM_Label8, LV_ALIGN_CENTER);                                                    // Align text to the center
    lv_label_set_text(ui_PWM_Label8, "Click Back");                                                      // Set button text
    lv_obj_set_style_text_color(ui_PWM_Label8, lv_color_hex(0xEE00FF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(ui_PWM_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_PWM_Label8, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    // Add event callbacks for all interactive objects
    lv_obj_add_event_cb(ui_PWM_Arc0, ui_event_PWM_Arc0, LV_EVENT_ALL, NULL);       // Add event callback for Arc 0
    lv_obj_add_event_cb(ui_PWM_Slider0, ui_event_PWM_Slider0, LV_EVENT_ALL, NULL); // Add event callback for Slider 0
    lv_obj_add_event_cb(ui_PWM_Switch1, ui_event_PWM_Switch1, LV_EVENT_ALL, NULL); // Add event callback for Switch 1
    lv_obj_add_event_cb(ui_PWM_Switch2, ui_event_PWM_Switch2, LV_EVENT_ALL, NULL); // Add event callback for Switch 2
    lv_obj_add_event_cb(ui_PWM_Switch3, ui_event_PWM_Switch3, LV_EVENT_ALL, NULL); // Add event callback for Switch 3
    lv_obj_add_event_cb(ui_PWM_Button0, ui_event_PWM_Button0, LV_EVENT_ALL, NULL); // Add event callback for Button 0
}
