// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: sq_ui

#include "../ui.h"

void ui_Main_RS485_screen_init(void)
{
    ui_Main_RS485 = lv_obj_create(NULL);                                                               // Create main RS485 screen object
    lv_obj_clear_flag(ui_Main_RS485, LV_OBJ_FLAG_SCROLLABLE);                                          /// Disable scrolling
    lv_obj_set_style_bg_img_src(ui_Main_RS485, &ui_img_log_on_png, LV_PART_MAIN | LV_STATE_DEFAULT);   // Set background image
    lv_obj_set_style_text_font(ui_Main_RS485, &ui_font_Chinese_Font, LV_PART_MAIN | LV_STATE_DEFAULT); // Set text font

    ui_RS485_Button1 = lv_btn_create(ui_Main_RS485);                                                      // Create Button 1
    lv_obj_set_width(ui_RS485_Button1, 400);                                                              // Set button width
    lv_obj_set_height(ui_RS485_Button1, 50);                                                              // Set button height
    lv_obj_set_x(ui_RS485_Button1, 0);                                                                    // Set X position
    lv_obj_set_y(ui_RS485_Button1, 50);                                                                   // Set Y position
    lv_obj_set_align(ui_RS485_Button1, LV_ALIGN_CENTER);                                                  // Align button at the center
    lv_obj_add_flag(ui_RS485_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);                                       /// Enable scrolling on focus
    lv_obj_clear_flag(ui_RS485_Button1, LV_OBJ_FLAG_SCROLLABLE);                                          /// Disable scrolling
    lv_obj_set_style_bg_color(ui_RS485_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set button background color
    lv_obj_set_style_bg_opa(ui_RS485_Button1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set button background opacity

    ui_RS485_Label1 = lv_label_create(ui_RS485_Button1);                                                   // Create label for Button 1
    lv_obj_set_width(ui_RS485_Label1, LV_SIZE_CONTENT);                                                    /// Set width based on content
    lv_obj_set_height(ui_RS485_Label1, LV_SIZE_CONTENT);                                                   /// Set height based on content
    lv_obj_set_align(ui_RS485_Label1, LV_ALIGN_CENTER);                                                    // Align label at the center
    lv_label_set_text(ui_RS485_Label1, "Click Back");                                                      // Set label text
    lv_obj_set_style_text_color(ui_RS485_Label1, lv_color_hex(0xEE00FF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(ui_RS485_Label1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_RS485_Label1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RS485_Keyboard1 = lv_keyboard_create(ui_Main_RS485);                                                  // Create keyboard object
    lv_obj_set_width(ui_RS485_Keyboard1, lv_pct(100));                                                       // Set keyboard width to 100% of parent
    lv_obj_set_height(ui_RS485_Keyboard1, lv_pct(50));                                                       // Set keyboard height to 50% of parent
    lv_obj_set_align(ui_RS485_Keyboard1, LV_ALIGN_BOTTOM_MID);                                               // Align keyboard at the bottom center
    lv_obj_add_flag(ui_RS485_Keyboard1, LV_OBJ_FLAG_HIDDEN);                                                 /// Hide keyboard initially
    lv_obj_set_style_text_font(ui_RS485_Keyboard1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT); // Set font for the keyboard
    lv_obj_set_style_bg_opa(ui_RS485_Keyboard1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                         // Set keyboard background opacity

    ui_RS485_Send = lv_obj_create(ui_Main_RS485);                                                          // Create RS485 Send panel
    lv_obj_set_width(ui_RS485_Send, lv_pct(50));                                                           // Set width to 50% of parent
    lv_obj_set_height(ui_RS485_Send, lv_pct(50));                                                          // Set height to 50% of parent
    lv_obj_clear_flag(ui_RS485_Send, LV_OBJ_FLAG_SCROLLABLE);                                              /// Disable scrolling
    lv_obj_set_style_bg_color(ui_RS485_Send, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color
    lv_obj_set_style_bg_opa(ui_RS485_Send, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set background opacity
    lv_obj_set_style_border_color(ui_RS485_Send, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color
    lv_obj_set_style_border_opa(ui_RS485_Send, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity

    ui_RS485_Send_Box = lv_label_create(ui_RS485_Send);                                                      // Create label for the RS485 Send box
    lv_obj_set_width(ui_RS485_Send_Box, LV_SIZE_CONTENT);                                                    /// Set width based on content
    lv_obj_set_height(ui_RS485_Send_Box, LV_SIZE_CONTENT);                                                   /// Set height based on content
    lv_label_set_text(ui_RS485_Send_Box, "RS485 Send Box");                                                  // Set text for the send box
    lv_obj_set_style_text_color(ui_RS485_Send_Box, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(ui_RS485_Send_Box, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_RS485_Send_Box, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RS485_Send_Area = lv_textarea_create(ui_RS485_Send);                                                   // Create text area for RS485 Send input
    lv_obj_set_width(ui_RS485_Send_Area, lv_pct(100));                                                        // Set width to 100% of parent
    lv_obj_set_height(ui_RS485_Send_Area, lv_pct(80));                                                        // Set height to 80% of parent
    lv_obj_set_align(ui_RS485_Send_Area, LV_ALIGN_BOTTOM_MID);                                                // Align text area at the bottom center
    lv_textarea_set_max_length(ui_RS485_Send_Area, 1024);
    lv_textarea_set_placeholder_text(ui_RS485_Send_Area, "Send...");                                          // Set placeholder text
    lv_obj_set_style_text_color(ui_RS485_Send_Area, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(ui_RS485_Send_Area, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_bg_color(ui_RS485_Send_Area, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set background color
    lv_obj_set_style_bg_opa(ui_RS485_Send_Area, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity

    lv_obj_set_style_radius(ui_RS485_Send_Area, 255, LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RS485_Send_Area, lv_color_hex(0xFFFFFF), LV_PART_CURSOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RS485_Send_Area, 0, LV_PART_CURSOR | LV_STATE_DEFAULT);

    ui_RS485_Button3 = lv_btn_create(ui_RS485_Send);                                                      // Create Button 3
    lv_obj_set_width(ui_RS485_Button3, 130);                                                              // Set button width
    lv_obj_set_height(ui_RS485_Button3, 35);                                                              // Set button height
    lv_obj_set_x(ui_RS485_Button3, 0);                                                                    // Set X position
    lv_obj_set_y(ui_RS485_Button3, -15);                                                                  // Set Y position
    lv_obj_set_align(ui_RS485_Button3, LV_ALIGN_TOP_RIGHT);                                               // Align button at top right
    lv_obj_add_flag(ui_RS485_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);                                       /// Enable scrolling on focus
    lv_obj_clear_flag(ui_RS485_Button3, LV_OBJ_FLAG_SCROLLABLE);                                          /// Disable scrolling
    lv_obj_set_style_bg_color(ui_RS485_Button3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set button background color
    lv_obj_set_style_bg_opa(ui_RS485_Button3, 100, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set button background opacity

    ui_RS485_Label3 = lv_label_create(ui_RS485_Button3);                                                   // Create label for Button 3
    lv_obj_set_width(ui_RS485_Label3, LV_SIZE_CONTENT);                                                    /// Set width based on content
    lv_obj_set_height(ui_RS485_Label3, LV_SIZE_CONTENT);                                                   /// Set height based on content
    lv_obj_set_align(ui_RS485_Label3, LV_ALIGN_CENTER);                                                    // Align label at the center
    lv_label_set_text(ui_RS485_Label3, "Baud rate");                                                       // Set label text
    lv_obj_set_style_text_color(ui_RS485_Label3, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(ui_RS485_Label3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_RS485_Label3, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RS485_Button4 = lv_btn_create(ui_RS485_Send);                                                      // Create Button 4
    lv_obj_set_width(ui_RS485_Button4, 80);                                                               // Set button width
    lv_obj_set_height(ui_RS485_Button4, 35);                                                              // Set button height
    lv_obj_set_x(ui_RS485_Button4, -140);                                                                 // Set X position
    lv_obj_set_y(ui_RS485_Button4, -15);                                                                  // Set Y position
    lv_obj_set_align(ui_RS485_Button4, LV_ALIGN_TOP_RIGHT);                                               // Align button at top right
    lv_obj_add_flag(ui_RS485_Button4, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);                  /// Hide button initially and enable scrolling on focus
    lv_obj_clear_flag(ui_RS485_Button4, LV_OBJ_FLAG_SCROLLABLE);                                          /// Disable scrolling
    lv_obj_set_style_bg_color(ui_RS485_Button4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set button background color
    lv_obj_set_style_bg_opa(ui_RS485_Button4, 100, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set button background opacity

    ui_RS485_Label4 = lv_label_create(ui_RS485_Button4);                                                   // Create label for Button 4
    lv_obj_set_width(ui_RS485_Label4, LV_SIZE_CONTENT);                                                    /// Set width based on content
    lv_obj_set_height(ui_RS485_Label4, LV_SIZE_CONTENT);                                                   /// Set height based on content
    lv_obj_set_align(ui_RS485_Label4, LV_ALIGN_CENTER);                                                    // Align label at the center
    lv_label_set_text(ui_RS485_Label4, "Save");                                                            // Set label text
    lv_obj_set_style_text_color(ui_RS485_Label4, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(ui_RS485_Label4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_RS485_Label4, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RS485_Read = lv_obj_create(ui_Main_RS485);                                                          // Create RS485 Read panel
    lv_obj_set_width(ui_RS485_Read, lv_pct(50));                                                           // Set width to 50% of parent
    lv_obj_set_height(ui_RS485_Read, lv_pct(50));                                                          // Set height to 50% of parent
    lv_obj_set_align(ui_RS485_Read, LV_ALIGN_TOP_RIGHT);                                                   // Align panel at top right
    lv_obj_clear_flag(ui_RS485_Read, LV_OBJ_FLAG_SCROLLABLE);                                              /// Disable scrolling
    lv_obj_set_style_bg_color(ui_RS485_Read, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color
    lv_obj_set_style_bg_opa(ui_RS485_Read, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set background opacity
    lv_obj_set_style_border_color(ui_RS485_Read, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color
    lv_obj_set_style_border_opa(ui_RS485_Read, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity

    ui_RS485_Read_Area = lv_textarea_create(ui_RS485_Read);                                                   // Create text area for RS485 Read input
    lv_obj_set_width(ui_RS485_Read_Area, lv_pct(100));                                                        // Set width to 100% of parent
    lv_obj_set_height(ui_RS485_Read_Area, lv_pct(80));                                                        // Set height to 80% of parent
    lv_obj_set_align(ui_RS485_Read_Area, LV_ALIGN_BOTTOM_MID);                                                // Align text area at the bottom center
    lv_textarea_set_max_length(ui_RS485_Read_Area, 1204);
    lv_textarea_set_placeholder_text(ui_RS485_Read_Area, "Read...");                                          // Set placeholder text
    lv_obj_set_style_text_color(ui_RS485_Read_Area, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(ui_RS485_Read_Area, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_bg_color(ui_RS485_Read_Area, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set background color
    lv_obj_set_style_bg_opa(ui_RS485_Read_Area, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity

    ui_RS485_Read_Box = lv_label_create(ui_RS485_Read);                                                      // Create label for the RS485 Read box
    lv_obj_set_width(ui_RS485_Read_Box, LV_SIZE_CONTENT);                                                    /// Set width based on content
    lv_obj_set_height(ui_RS485_Read_Box, LV_SIZE_CONTENT);                                                   /// Set height based on content
    lv_label_set_text(ui_RS485_Read_Box, "RS485 Read Box");                                                  // Set label text
    lv_obj_set_style_text_color(ui_RS485_Read_Box, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(ui_RS485_Read_Box, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_RS485_Read_Box, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RS485_Button2 = lv_btn_create(ui_RS485_Read);                                                      // Create Button 2
    lv_obj_set_width(ui_RS485_Button2, 80);                                                               // Set button width
    lv_obj_set_height(ui_RS485_Button2, 35);                                                              // Set button height
    lv_obj_set_x(ui_RS485_Button2, 0);                                                                    // Set X position
    lv_obj_set_y(ui_RS485_Button2, -15);                                                                  // Set Y position
    lv_obj_set_align(ui_RS485_Button2, LV_ALIGN_TOP_RIGHT);                                               // Align button at top right
    lv_obj_add_flag(ui_RS485_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);                                       /// Enable scrolling on focus
    lv_obj_clear_flag(ui_RS485_Button2, LV_OBJ_FLAG_SCROLLABLE);                                          /// Disable scrolling
    lv_obj_set_style_bg_color(ui_RS485_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set button background color
    lv_obj_set_style_bg_opa(ui_RS485_Button2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set button background opacity

    ui_RS485_Label2 = lv_label_create(ui_RS485_Button2);                                                   // Create label for Button 2
    lv_obj_set_width(ui_RS485_Label2, LV_SIZE_CONTENT);                                                    /// Set width based on content
    lv_obj_set_height(ui_RS485_Label2, LV_SIZE_CONTENT);                                                   /// Set height based on content
    lv_obj_set_align(ui_RS485_Label2, LV_ALIGN_CENTER);                                                    // Align label at the center
    lv_label_set_text(ui_RS485_Label2, "Clear");                                                           // Set label text
    lv_obj_set_style_text_color(ui_RS485_Label2, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(ui_RS485_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_RS485_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RS485_Roller1 = lv_roller_create(ui_Main_RS485); // Create roller for baud rate selection
    lv_roller_set_options(ui_RS485_Roller1,
                          "4800\n9600\n14400\n19200\n38400\n56000\n57600\n115200\n230400\n256000\n460800\n500000\n512000\n600000\n750000\n921600",
                          LV_ROLLER_MODE_INFINITE);                                                         // Set options for baud rate
    lv_roller_set_selected(ui_RS485_Roller1, 7, LV_ANIM_OFF);                                               // Set initial selected option (115200)
    lv_obj_set_height(ui_RS485_Roller1, 230);                                                               // Set height of the roller
    lv_obj_set_width(ui_RS485_Roller1, LV_SIZE_CONTENT);                                                    /// Set width based on content
    lv_obj_set_align(ui_RS485_Roller1, LV_ALIGN_CENTER);                                                    // Align roller at the center
    lv_obj_add_flag(ui_RS485_Roller1, LV_OBJ_FLAG_HIDDEN);                                                  /// Hide roller initially
    lv_obj_set_style_text_color(ui_RS485_Roller1, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(ui_RS485_Roller1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_RS485_Roller1, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RS485_Roller1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set background color
    lv_obj_set_style_bg_opa(ui_RS485_Roller1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity

    // Add event handlers for buttons and areas
    lv_obj_add_event_cb(ui_RS485_Button1, ui_event_RS485_Button1, LV_EVENT_ALL, NULL);     // Event callback for Button 1
    lv_keyboard_set_textarea(ui_RS485_Keyboard1, ui_RS485_Read_Area);                      // Set the text area for the keyboard
    lv_obj_add_event_cb(ui_RS485_Send_Area, ui_event_RS485_Send_Area, LV_EVENT_ALL, NULL); // Event callback for Send Area
    lv_obj_add_event_cb(ui_RS485_Button3, ui_event_RS485_Button3, LV_EVENT_ALL, NULL);     // Event callback for Button 3
    lv_obj_add_event_cb(ui_RS485_Button4, ui_event_RS485_Button4, LV_EVENT_ALL, NULL);     // Event callback for Button 4
    lv_obj_add_event_cb(ui_RS485_Button2, ui_event_RS485_Button2, LV_EVENT_ALL, NULL);     // Event callback for Button 2
}
