// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: sq_ui

#include "../ui.h"

void ui_Main_WIFI_screen_init(void)
{
    // Create the main Wi-Fi screen container
    ui_Main_WIFI = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Main_WIFI, LV_OBJ_FLAG_SCROLLABLE); // Disable scrolling

    // Create tab view for Wi-Fi settings
    ui_WIFI = lv_tabview_create(ui_Main_WIFI, LV_DIR_TOP, 50);
    lv_obj_set_width(ui_WIFI, lv_pct(100));                                                      // Full width
    lv_obj_set_height(ui_WIFI, lv_pct(100));                                                     // Full height
    lv_obj_set_align(ui_WIFI, LV_ALIGN_CENTER);                                                  // Center alignment
    lv_obj_clear_flag(ui_WIFI, LV_OBJ_FLAG_SCROLLABLE);                                          // Disable scrolling for the tabview
    lv_obj_set_style_bg_img_src(ui_WIFI, &ui_img_log_on_png, LV_PART_MAIN | LV_STATE_DEFAULT);   // Set background image
    // lv_obj_set_style_text_font(ui_WIFI, &ui_font_Chinese_Font, LV_PART_MAIN | LV_STATE_DEFAULT); // Set text font
    lv_obj_set_style_text_font(ui_WIFI, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    // Style tab buttons
    lv_obj_set_style_text_color(lv_tabview_get_tab_btns(ui_WIFI), lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(lv_tabview_get_tab_btns(ui_WIFI), 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_bg_color(lv_tabview_get_tab_btns(ui_WIFI), lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set background color
    lv_obj_set_style_bg_opa(lv_tabview_get_tab_btns(ui_WIFI), 0, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity

    // Create the "STA" (station) tab
    ui_WIFI_STA = lv_tabview_add_tab(ui_WIFI, "STA");
    lv_obj_set_style_bg_color(ui_WIFI_STA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set background color
    lv_obj_set_style_bg_opa(ui_WIFI_STA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set background opacity

    // Create scan container for "STA" tab
    ui_WIFI_SCAN_STA = lv_obj_create(ui_WIFI_STA);
    lv_obj_set_width(ui_WIFI_SCAN_STA, lv_pct(100));                                                          // Full width
    lv_obj_set_height(ui_WIFI_SCAN_STA, lv_pct(100));                                                         // Full height
    lv_obj_clear_flag(ui_WIFI_SCAN_STA, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling
    lv_obj_set_style_bg_color(ui_WIFI_SCAN_STA, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color
    lv_obj_set_style_bg_opa(ui_WIFI_SCAN_STA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set background opacity
    lv_obj_set_style_border_color(ui_WIFI_SCAN_STA, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color
    lv_obj_set_style_border_opa(ui_WIFI_SCAN_STA, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity

    // Create button for "Click Back" functionality
    ui_WIFI_Button0 = lv_btn_create(ui_WIFI_SCAN_STA);
    lv_obj_set_width(ui_WIFI_Button0, 137);                                                              // Set button width
    lv_obj_set_height(ui_WIFI_Button0, 50);                                                              // Set button height
    lv_obj_add_flag(ui_WIFI_Button0, LV_OBJ_FLAG_SCROLL_ON_FOCUS);                                       // Enable scrolling on focus
    lv_obj_clear_flag(ui_WIFI_Button0, LV_OBJ_FLAG_SCROLLABLE);                                          // Disable scrolling
    lv_obj_set_style_bg_color(ui_WIFI_Button0, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set button background color
    lv_obj_set_style_bg_opa(ui_WIFI_Button0, 100, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set button background opacity

    // Create label for "Click Back" button
    ui_WIFI_Label0 = lv_label_create(ui_WIFI_Button0);
    lv_obj_set_width(ui_WIFI_Label0, LV_SIZE_CONTENT);                                                    // Set label width based on content
    lv_obj_set_height(ui_WIFI_Label0, LV_SIZE_CONTENT);                                                   // Set label height based on content
    lv_obj_set_align(ui_WIFI_Label0, LV_ALIGN_CENTER);                                                    // Align label at the center
    lv_label_set_text(ui_WIFI_Label0, "Click Back");                                                      // Set button label text
    lv_obj_set_style_text_color(ui_WIFI_Label0, lv_color_hex(0xEE00FF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color
    lv_obj_set_style_text_opa(ui_WIFI_Label0, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity
    lv_obj_set_style_text_font(ui_WIFI_Label0, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);
    
    // Create a switch for Wi-Fi settings (ON/OFF)
    ui_WIFI_OPEN = lv_switch_create(ui_WIFI_SCAN_STA);
    lv_obj_set_width(ui_WIFI_OPEN, 50);                 // Set switch width
    lv_obj_set_height(ui_WIFI_OPEN, 30);                // Set switch height
    lv_obj_set_x(ui_WIFI_OPEN, 0);                      // Set X position
    lv_obj_set_y(ui_WIFI_OPEN, 12);                     // Set Y position
    lv_obj_set_align(ui_WIFI_OPEN, LV_ALIGN_TOP_RIGHT); // Align switch to the top-right corner

    // Create a window for displaying Wi-Fi network list
    ui_WIFI_List_Win = lv_obj_create(ui_WIFI_SCAN_STA);
    lv_obj_set_width(ui_WIFI_List_Win, lv_pct(50));                                                           // Set window width
    lv_obj_set_height(ui_WIFI_List_Win, lv_pct(80));                                                          // Set window height
    lv_obj_set_align(ui_WIFI_List_Win, LV_ALIGN_BOTTOM_LEFT);                                                 // Align window to the bottom-left corner
    lv_obj_clear_flag(ui_WIFI_List_Win, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling
    lv_obj_set_style_bg_color(ui_WIFI_List_Win, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set window background color
    lv_obj_set_style_bg_opa(ui_WIFI_List_Win, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set window background opacity
    lv_obj_set_style_border_color(ui_WIFI_List_Win, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set window border color
    lv_obj_set_style_border_opa(ui_WIFI_List_Win, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set window border opacity
    lv_obj_set_style_text_font(ui_WIFI_List_Win, &ui_font_Chinese_Font, LV_PART_MAIN | LV_STATE_DEFAULT); // Set text font

    /* Create a Wi-Fi scan list */
    ui_WIFI_SCAN_List = lv_list_create(ui_WIFI_List_Win);
    lv_obj_set_width(ui_WIFI_SCAN_List, lv_pct(100));                                                        // Set the width to 100% of parent container
    lv_obj_set_height(ui_WIFI_SCAN_List, lv_pct(100));                                                       // Set the height to 119% of parent container
    lv_obj_set_x(ui_WIFI_SCAN_List, 0);                                                                      // Set the x position to 0
    lv_obj_set_y(ui_WIFI_SCAN_List, -22);                                                                    // Set the y position to -22
    lv_obj_set_scrollbar_mode(ui_WIFI_SCAN_List, LV_SCROLLBAR_MODE_OFF);                                     // Disable scrollbar
    lv_obj_add_flag(ui_WIFI_SCAN_List, LV_OBJ_FLAG_HIDDEN); 
    lv_obj_set_style_bg_color(ui_WIFI_SCAN_List, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);                                                 // Initially hide the list
    lv_obj_set_style_bg_opa(ui_WIFI_SCAN_List, 160, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity to 0 (transparent)
    lv_obj_set_style_text_color(ui_WIFI_SCAN_List, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_SCAN_List, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to 255 (fully opaque)

    /* Create a spinner for loading indication */
    ui_WIFI_Spinner = lv_spinner_create(ui_WIFI_List_Win, 1000, 90); // Create a spinner with 1000ms rotation duration
    lv_obj_set_width(ui_WIFI_Spinner, 80);                           // Set spinner width to 80
    lv_obj_set_height(ui_WIFI_Spinner, 80);                          // Set spinner height to 80
    lv_obj_set_align(ui_WIFI_Spinner, LV_ALIGN_CENTER);              // Align spinner to the center of the parent container
    lv_obj_add_flag(ui_WIFI_Spinner, LV_OBJ_FLAG_HIDDEN);            // Initially hide the spinner
    lv_obj_clear_flag(ui_WIFI_Spinner, LV_OBJ_FLAG_CLICKABLE);       // Disable clicking on the spinner

    /* Create Wi-Fi details window */
    ui_WIFI_Details_Win = lv_obj_create(ui_WIFI_SCAN_STA);
    lv_obj_set_width(ui_WIFI_Details_Win, lv_pct(50));                                                       // Set width to 50% of the parent container
    lv_obj_set_height(ui_WIFI_Details_Win, lv_pct(80));                                                      // Set height to 80% of the parent container
    lv_obj_set_align(ui_WIFI_Details_Win, LV_ALIGN_BOTTOM_RIGHT);                                            // Align window to the bottom-right of the parent container
    lv_obj_add_flag(ui_WIFI_Details_Win, LV_OBJ_FLAG_HIDDEN);                                                // Initially hide the window
    lv_obj_clear_flag(ui_WIFI_Details_Win, LV_OBJ_FLAG_SCROLLABLE);                                          // Disable scrolling
    lv_obj_set_style_bg_color(ui_WIFI_Details_Win, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT); // Set background color to white
    lv_obj_set_style_bg_opa(ui_WIFI_Details_Win, 160, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set background opacity to 0 (transparent)
    lv_obj_set_style_text_font(ui_WIFI_Details_Win, &ui_font_Chinese_Font, LV_PART_MAIN | LV_STATE_DEFAULT); // Set text font

    /* Create and configure SSID label */
    ui_WIFI_Name = lv_label_create(ui_WIFI_Details_Win);
    lv_obj_set_width(ui_WIFI_Name, lv_pct(100));                                                        // Set label width to 100% of parent container
    lv_obj_set_height(ui_WIFI_Name, lv_pct(10));                                                        // Set label height to 10% of parent container
    lv_obj_set_x(ui_WIFI_Name, 0);                                                                      // Set x position to 0
    lv_obj_set_y(ui_WIFI_Name, 30);                                                                     // Set y position to 30
    lv_label_set_long_mode(ui_WIFI_Name, LV_LABEL_LONG_SCROLL);                                         // Enable horizontal scrolling for long text
    lv_label_set_text(ui_WIFI_Name, "SSID JSBPI");                                                      // Set the text to display SSID
    lv_obj_set_style_text_color(ui_WIFI_Name, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_Name, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to 255 (fully opaque)

    /* Create and configure Authentication mode label */
    ui_WIFI_Aurhmode = lv_label_create(ui_WIFI_Details_Win);
    lv_obj_set_width(ui_WIFI_Aurhmode, lv_pct(100));                                                        // Set label width to 100% of parent container
    lv_obj_set_height(ui_WIFI_Aurhmode, lv_pct(10));                                                        // Set label height to 10% of parent container
    lv_obj_set_x(ui_WIFI_Aurhmode, 0);                                                                      // Set x position to 0
    lv_obj_set_y(ui_WIFI_Aurhmode, 60);                                                                     // Set y position to 60
    lv_label_set_long_mode(ui_WIFI_Aurhmode, LV_LABEL_LONG_SCROLL);                                         // Enable horizontal scrolling for long text
    lv_label_set_text(ui_WIFI_Aurhmode, "Authmode WIFI_AUTH_WPA2_PSK");                                     // Set text to show authentication mode
    lv_obj_set_style_text_color(ui_WIFI_Aurhmode, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_Aurhmode, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to 255 (fully opaque)

    /* Create and configure Pairwise Cipher label */
    ui_WIFI_Pairwise = lv_label_create(ui_WIFI_Details_Win);
    lv_obj_set_width(ui_WIFI_Pairwise, lv_pct(100));                                                        // Set label width to 100% of parent container
    lv_obj_set_height(ui_WIFI_Pairwise, lv_pct(10));                                                        // Set label height to 10% of parent container
    lv_obj_set_x(ui_WIFI_Pairwise, 0);                                                                      // Set x position to 0
    lv_obj_set_y(ui_WIFI_Pairwise, 90);                                                                     // Set y position to 90
    lv_label_set_text(ui_WIFI_Pairwise, "Pairwise Cipher WIFI_CIPHER_TYPE_CCMP");                           // Set text to show pairwise cipher
    lv_label_set_long_mode(ui_WIFI_Pairwise, LV_LABEL_LONG_SCROLL);                                         // Enable horizontal scrolling for long text
    lv_obj_set_style_text_color(ui_WIFI_Pairwise, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_Pairwise, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to 255 (fully opaque)

    /* Create Group Cipher label */
    ui_WIFI_Group = lv_label_create(ui_WIFI_Details_Win);
    lv_obj_set_width(ui_WIFI_Group, lv_pct(100));                                                        // Set label width to 100% of parent container
    lv_obj_set_height(ui_WIFI_Group, lv_pct(10));                                                        // Set label height to 10% of parent container
    lv_obj_set_x(ui_WIFI_Group, 0);                                                                      // Set x position to 0
    lv_obj_set_y(ui_WIFI_Group, 120);                                                                    // Set y position to 120
    lv_label_set_long_mode(ui_WIFI_Group, LV_LABEL_LONG_SCROLL);                                         // Enable horizontal scrolling for long text
    lv_label_set_text(ui_WIFI_Group, "Group Cipher WIFI_CIPHER_TYPE_CCMP");                              // Set text to show group cipher
    lv_obj_set_style_text_color(ui_WIFI_Group, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_Group, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to 255 (fully opaque)

    /* Create Channel label */
    ui_WIFI_Channel = lv_label_create(ui_WIFI_Details_Win);
    lv_obj_set_width(ui_WIFI_Channel, lv_pct(100));                                                        // Set label width to 100% of parent container
    lv_obj_set_height(ui_WIFI_Channel, lv_pct(10));                                                        // Set label height to 10% of parent container
    lv_obj_set_x(ui_WIFI_Channel, 0);                                                                      // Set x position to 0
    lv_obj_set_y(ui_WIFI_Channel, 150);                                                                    // Set y position to 150
    lv_label_set_long_mode(ui_WIFI_Channel, LV_LABEL_LONG_SCROLL);                                         // Enable horizontal scrolling for long text
    lv_label_set_text(ui_WIFI_Channel, "Channel 5");                                                       // Set text to show Wi-Fi channel
    lv_obj_set_style_text_color(ui_WIFI_Channel, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_Channel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to 255 (fully opaque)

    /* Create IP address label */
    ui_WIFI_IP = lv_label_create(ui_WIFI_Details_Win);
    lv_obj_set_width(ui_WIFI_IP, LV_SIZE_CONTENT);                                                    // Set width to content size
    lv_obj_set_height(ui_WIFI_IP, LV_SIZE_CONTENT);                                                   // Set height to content size
    lv_label_set_text(ui_WIFI_IP, "IP 192.168.10.161");                                               // Set text to show IP address
    lv_obj_add_flag(ui_WIFI_IP, LV_OBJ_FLAG_HIDDEN);                                                  // Initially hide the label
    lv_obj_set_style_text_color(ui_WIFI_IP, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_IP, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to 255 (fully opaque)

    /* Create Wi-Fi connection button */
    ui_WIFI_Connection_BUTTON = lv_btn_create(ui_WIFI_Details_Win);
    lv_obj_set_width(ui_WIFI_Connection_BUTTON, 200);                                                              // Set button width to 120
    lv_obj_set_height(ui_WIFI_Connection_BUTTON, 50);                                                              // Set button height to 50
    lv_obj_set_align(ui_WIFI_Connection_BUTTON, LV_ALIGN_BOTTOM_MID);                                              // Align button to the bottom center of parent container
    lv_obj_add_flag(ui_WIFI_Connection_BUTTON, LV_OBJ_FLAG_SCROLL_ON_FOCUS);                                       // Enable scroll on focus flag
    lv_obj_clear_flag(ui_WIFI_Connection_BUTTON, LV_OBJ_FLAG_SCROLLABLE);                                          // Disable scrollable flag
    lv_obj_set_style_bg_color(ui_WIFI_Connection_BUTTON, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set button background color to white
    lv_obj_set_style_bg_opa(ui_WIFI_Connection_BUTTON, 100, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set button background opacity to 0 (transparent)

    /* Create label inside the Wi-Fi connection button */
    ui_Connection = lv_label_create(ui_WIFI_Connection_BUTTON);
    lv_obj_set_width(ui_Connection, LV_SIZE_CONTENT);                                                    // Set width to content size
    lv_obj_set_height(ui_Connection, LV_SIZE_CONTENT);                                                   // Set height to content size
    lv_obj_set_align(ui_Connection, LV_ALIGN_CENTER);                                                    // Align label to the center of the button
    lv_label_set_text(ui_Connection, "Connection");                                                      // Set label text to "Connection"
    lv_obj_set_style_text_color(ui_Connection, lv_color_hex(0xEE00FF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to grey
    lv_obj_set_style_text_opa(ui_Connection, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to 255 (fully opaque)
    lv_obj_set_style_text_font(ui_Connection, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Create Wi-Fi password input field */
    ui_WIFI_INPUT_PWD = lv_textarea_create(ui_WIFI_SCAN_STA);
    lv_obj_set_width(ui_WIFI_INPUT_PWD, 300);                                                                  // Set input field width to 300
    lv_obj_set_height(ui_WIFI_INPUT_PWD, LV_SIZE_CONTENT);                                                     // Set input field height to content size
    lv_obj_set_align(ui_WIFI_INPUT_PWD, LV_ALIGN_CENTER);                                                      // Align input field to the center of the parent container
    lv_textarea_set_max_length(ui_WIFI_INPUT_PWD, 1024);                                                       // Set maximum length for input to 1024 characters
    lv_textarea_set_placeholder_text(ui_WIFI_INPUT_PWD, "Enter password...");                                  // Set placeholder text
    lv_textarea_set_one_line(ui_WIFI_INPUT_PWD, true);                                                         // Set the input field to one line mode
    lv_textarea_set_password_mode(ui_WIFI_INPUT_PWD, WIFI_DIS_PWD);                                            // Set password mode (hides text)
    lv_obj_add_flag(ui_WIFI_INPUT_PWD, LV_OBJ_FLAG_HIDDEN);                                                    // Initially hide the input field
    lv_obj_set_style_text_color(ui_WIFI_INPUT_PWD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_INPUT_PWD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set text opacity to 255 (fully opaque)
    lv_obj_set_style_bg_color(ui_WIFI_INPUT_PWD, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color to dark blue
    lv_obj_set_style_bg_opa(ui_WIFI_INPUT_PWD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity to 255 (fully opaque)
    lv_obj_set_style_border_color(ui_WIFI_INPUT_PWD, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color to black
    lv_obj_set_style_border_opa(ui_WIFI_INPUT_PWD, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set border opacity to 255 (fully opaque)

    /* Create an icon (eye) for password visibility toggle */
    ui_WIFI_EYE = lv_img_create(ui_WIFI_INPUT_PWD);
    lv_img_set_src(ui_WIFI_EYE, &ui_img_eye_png);                                  // Set the eye icon image source
    lv_obj_set_width(ui_WIFI_EYE, 34);                                             // Set icon width to 34
    lv_obj_set_height(ui_WIFI_EYE, 20);                                            // Set icon height to 20
    lv_obj_set_align(ui_WIFI_EYE, LV_ALIGN_RIGHT_MID);                             // Align the icon to the right middle of the input field
    lv_obj_add_flag(ui_WIFI_EYE, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST); // Add clickable and advanced hit test flags
    lv_obj_clear_flag(ui_WIFI_EYE, LV_OBJ_FLAG_SCROLLABLE);                        // Disable scrollable flag
    lv_img_set_zoom(ui_WIFI_EYE, 255);                                             // Set zoom level for the image (no zoom)

    /* Create Wi-Fi input keyboard */
    ui_WIFI_INPUT_KEYBOARD = lv_keyboard_create(ui_WIFI_SCAN_STA);
    lv_obj_set_width(ui_WIFI_INPUT_KEYBOARD, lv_pct(100));                                                        // Set keyboard width to 100% of parent container
    lv_obj_set_height(ui_WIFI_INPUT_KEYBOARD, lv_pct(50));                                                        // Set keyboard height to 50% of parent container
    lv_obj_set_x(ui_WIFI_INPUT_KEYBOARD, 0);                                                                      // Set x position to 0
    lv_obj_set_y(ui_WIFI_INPUT_KEYBOARD, 15);                                                                     // Set y position to 15
    lv_obj_set_align(ui_WIFI_INPUT_KEYBOARD, LV_ALIGN_BOTTOM_MID);                                                // Align keyboard to the bottom center of parent container
    lv_obj_add_flag(ui_WIFI_INPUT_KEYBOARD, LV_OBJ_FLAG_HIDDEN);                                                  // Initially hide the keyboard
    lv_obj_set_style_bg_color(ui_WIFI_INPUT_KEYBOARD, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set background color to white
    lv_obj_set_style_bg_opa(ui_WIFI_INPUT_KEYBOARD, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity to 0 (transparent)
    lv_obj_set_style_text_font(ui_WIFI_INPUT_KEYBOARD, &lv_font_montserrat_14, LV_PART_ITEMS | LV_STATE_DEFAULT); // Set font style for keyboard items

    /* Create Wi-Fi connection waiting spinner */
    ui_WIFI_Wait_CONNECTION = lv_spinner_create(ui_WIFI_SCAN_STA, 1000, 90);
    lv_obj_set_width(ui_WIFI_Wait_CONNECTION, 80);                     // Set spinner width to 80
    lv_obj_set_height(ui_WIFI_Wait_CONNECTION, 80);                    // Set spinner height to 80
    lv_obj_set_align(ui_WIFI_Wait_CONNECTION, LV_ALIGN_CENTER);        // Align spinner to the center of parent container
    lv_obj_add_flag(ui_WIFI_Wait_CONNECTION, LV_OBJ_FLAG_HIDDEN);      // Initially hide the spinner
    lv_obj_clear_flag(ui_WIFI_Wait_CONNECTION, LV_OBJ_FLAG_CLICKABLE); // Make spinner non-clickable

    /* Create Wi-Fi password error label */
    ui_WIFI_PWD_Error = lv_label_create(ui_WIFI_SCAN_STA);
    lv_obj_set_width(ui_WIFI_PWD_Error, LV_SIZE_CONTENT);                                                    // Set width to content size
    lv_obj_set_height(ui_WIFI_PWD_Error, LV_SIZE_CONTENT);                                                   // Set height to content size
    lv_obj_set_x(ui_WIFI_PWD_Error, 0);                                                                      // Set x position to 0
    lv_obj_set_y(ui_WIFI_PWD_Error, 80);                                                                     // Set y position to 80
    lv_obj_set_align(ui_WIFI_PWD_Error, LV_ALIGN_TOP_MID);                                                   // Align label to the top center of parent container
    lv_label_set_text(ui_WIFI_PWD_Error, "Wrong password");                                                  // Set label text to "Wrong password"
    lv_obj_add_flag(ui_WIFI_PWD_Error, LV_OBJ_FLAG_HIDDEN);                                                  // Initially hide the error label
    lv_obj_set_style_text_color(ui_WIFI_PWD_Error, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to red
    lv_obj_set_style_text_opa(ui_WIFI_PWD_Error, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to 255 (fully opaque)
    lv_obj_set_style_text_font(ui_WIFI_PWD_Error, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Create new tab in Wi-Fi view for AP settings */
    ui_WIFI_AP = lv_tabview_add_tab(ui_WIFI, "AP"); // Add a new tab titled "AP" to the Wi-Fi tab view

    /* Create a container for the Open AP settings */
    ui_WIFI_OPEN_AP_ = lv_obj_create(ui_WIFI_AP);
    lv_obj_set_width(ui_WIFI_OPEN_AP_, lv_pct(100));                                                          // Set container width to 100% of parent container
    lv_obj_set_height(ui_WIFI_OPEN_AP_, lv_pct(100));                                                         // Set container height to 100% of parent container
    lv_obj_set_align(ui_WIFI_OPEN_AP_, LV_ALIGN_CENTER);                                                      // Align container to the center of the parent container
    lv_obj_clear_flag(ui_WIFI_OPEN_AP_, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling for this container
    lv_obj_set_style_bg_color(ui_WIFI_OPEN_AP_, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color to white
    lv_obj_set_style_bg_opa(ui_WIFI_OPEN_AP_, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set background opacity to 0 (transparent)
    lv_obj_set_style_border_color(ui_WIFI_OPEN_AP_, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color to black
    lv_obj_set_style_border_opa(ui_WIFI_OPEN_AP_, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity to 0 (transparent)

    /* Create "Click Back" button in Open AP settings */
    ui_WIFI_Button2 = lv_btn_create(ui_WIFI_OPEN_AP_);
    lv_obj_set_width(ui_WIFI_Button2, 140);                                                              // Set button width to 120
    lv_obj_set_height(ui_WIFI_Button2, 50);                                                              // Set button height to 50
    lv_obj_add_flag(ui_WIFI_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);                                       // Enable scrolling on focus for the button
    lv_obj_clear_flag(ui_WIFI_Button2, LV_OBJ_FLAG_SCROLLABLE);                                          // Disable scrolling for this button
    lv_obj_set_style_bg_color(ui_WIFI_Button2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set button background color to white
    lv_obj_set_style_bg_opa(ui_WIFI_Button2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set button background opacity to 0 (transparent)

    /* Create label inside the "Click Back" button */
    ui_WIFI_Label2 = lv_label_create(ui_WIFI_Button2);
    lv_obj_set_width(ui_WIFI_Label2, LV_SIZE_CONTENT);                                                    // Set label width to content size
    lv_obj_set_height(ui_WIFI_Label2, LV_SIZE_CONTENT);                                                   // Set label height to content size
    lv_obj_set_align(ui_WIFI_Label2, LV_ALIGN_CENTER);                                                    // Align label to the center of the button
    lv_label_set_text(ui_WIFI_Label2, "Click Back");                                                      // Set label text to "Click Back"
    lv_obj_set_style_text_color(ui_WIFI_Label2, lv_color_hex(0xEE00FF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to grey
    lv_obj_set_style_text_opa(ui_WIFI_Label2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to 255 (fully opaque)
    lv_obj_set_style_text_font(ui_WIFI_Label2, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Create container for AP settings information */
    ui_WIFI_AP_Information = lv_obj_create(ui_WIFI_OPEN_AP_);
    lv_obj_set_width(ui_WIFI_AP_Information, lv_pct(55));                                                           // Set width to 55% of parent container
    lv_obj_set_height(ui_WIFI_AP_Information, lv_pct(84));                                                          // Set height to 84% of parent container
    lv_obj_set_align(ui_WIFI_AP_Information, LV_ALIGN_BOTTOM_LEFT);                                                 // Align to the bottom left of parent container
    lv_obj_clear_flag(ui_WIFI_AP_Information, LV_OBJ_FLAG_SCROLLABLE);                                              // Disable scrolling for this container
    lv_obj_set_style_bg_color(ui_WIFI_AP_Information, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color to white
    lv_obj_set_style_bg_opa(ui_WIFI_AP_Information, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set background opacity to 0 (transparent)
    lv_obj_set_style_border_color(ui_WIFI_AP_Information, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color to black
    lv_obj_set_style_border_opa(ui_WIFI_AP_Information, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity to 0 (transparent)

    /* Create AP name input field */
    ui_WIFI_AP_NAME = lv_textarea_create(ui_WIFI_AP_Information);
    lv_obj_set_width(ui_WIFI_AP_NAME, 295);                                                                // Set width to 295
    lv_obj_set_height(ui_WIFI_AP_NAME, LV_SIZE_CONTENT);                                                   // Set height based on content (70)
    lv_obj_set_x(ui_WIFI_AP_NAME, 50);                                                                     // Set x position to 50
    lv_obj_set_y(ui_WIFI_AP_NAME, -120);                                                                   // Set y position to -120
    lv_obj_set_align(ui_WIFI_AP_NAME, LV_ALIGN_CENTER);                                                    // Align to the center of the parent container
    lv_textarea_set_text(ui_WIFI_AP_NAME, "ESP32-S3-Touch-LCD-7");                                         // Set default text for SSID
    lv_textarea_set_placeholder_text(ui_WIFI_AP_NAME, "Please enter SSID...");                             // Set placeholder text
    lv_textarea_set_one_line(ui_WIFI_AP_NAME, true);                                                       // Allow only one line for input
    lv_obj_set_style_text_color(ui_WIFI_AP_NAME, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_AP_NAME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully opaque
    lv_obj_set_style_bg_color(ui_WIFI_AP_NAME, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set background color to white
    lv_obj_set_style_bg_opa(ui_WIFI_AP_NAME, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity to 0 (transparent)

    /* Create AP password input field */
    ui_WIFI_AP_Password = lv_textarea_create(ui_WIFI_AP_Information);
    lv_obj_set_width(ui_WIFI_AP_Password, 295);                                                                // Set width to 295
    lv_obj_set_height(ui_WIFI_AP_Password, LV_SIZE_CONTENT);                                                   // Set height based on content (70)
    lv_obj_set_x(ui_WIFI_AP_Password, 50);                                                                     // Set x position to 50
    lv_obj_set_y(ui_WIFI_AP_Password, -70);                                                                    // Set y position to -70
    lv_obj_set_align(ui_WIFI_AP_Password, LV_ALIGN_CENTER);                                                    // Align to the center of the parent container
    lv_textarea_set_text(ui_WIFI_AP_Password, "66668888");                                                     // Set default password
    lv_textarea_set_placeholder_text(ui_WIFI_AP_Password, "Please enter Password...");                         // Set placeholder text
    lv_textarea_set_one_line(ui_WIFI_AP_Password, true);                                                       // Allow only one line for input
    lv_textarea_set_password_mode(ui_WIFI_AP_Password, WIFI_AP_PWD);                                           // Set password mode for masking input
    lv_obj_set_style_text_color(ui_WIFI_AP_Password, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_AP_Password, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully opaque
    lv_obj_set_style_bg_color(ui_WIFI_AP_Password, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set background color to white
    lv_obj_set_style_bg_opa(ui_WIFI_AP_Password, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity to 0 (transparent)

    /* Create eye icon to toggle password visibility */
    ui_WIFI_AP_EYE = lv_img_create(ui_WIFI_AP_Password);
    lv_img_set_src(ui_WIFI_AP_EYE, &ui_img_eye_png);                                  // Set image source for eye icon (assuming ui_img_eye_png is defined elsewhere)
    lv_obj_set_width(ui_WIFI_AP_EYE, 34);                                             // Set width of the eye icon
    lv_obj_set_height(ui_WIFI_AP_EYE, 20);                                            // Set height of the eye icon
    lv_obj_set_align(ui_WIFI_AP_EYE, LV_ALIGN_RIGHT_MID);                             // Align eye icon to the right middle of the password input field
    lv_obj_add_flag(ui_WIFI_AP_EYE, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST); // Make the eye icon clickable and enable advanced hit testing
    lv_obj_clear_flag(ui_WIFI_AP_EYE, LV_OBJ_FLAG_SCROLLABLE);                        // Disable scrolling for the eye icon
    lv_img_set_zoom(ui_WIFI_AP_EYE, 255);                                             // Set image zoom level to fully zoomed-in (no scaling)

    /* Create AP channel input field */
    ui_WIFI_AP_Channel = lv_textarea_create(ui_WIFI_AP_Information);
    lv_obj_set_width(ui_WIFI_AP_Channel, 295);                                                                // Set width to 295
    lv_obj_set_height(ui_WIFI_AP_Channel, LV_SIZE_CONTENT);                                                   // Set height based on content (70)
    lv_obj_set_x(ui_WIFI_AP_Channel, 50);                                                                     // Set x position to 50
    lv_obj_set_y(ui_WIFI_AP_Channel, -20);                                                                    // Set y position to -20
    lv_obj_set_align(ui_WIFI_AP_Channel, LV_ALIGN_CENTER);                                                    // Align to the center of the parent container
    lv_textarea_set_text(ui_WIFI_AP_Channel, "1");                                                            // Set default channel number to 1
    lv_textarea_set_placeholder_text(ui_WIFI_AP_Channel, "Please enter 1 - 14...");                           // Set placeholder text for channel range
    lv_textarea_set_one_line(ui_WIFI_AP_Channel, true);                                                       // Allow only one line for input
    lv_obj_set_style_text_color(ui_WIFI_AP_Channel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_AP_Channel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully opaque
    lv_obj_set_style_bg_color(ui_WIFI_AP_Channel, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set background color to white
    lv_obj_set_style_bg_opa(ui_WIFI_AP_Channel, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity to 0 (transparent)

    /* Create label for SSID (Wi-Fi Access Point Name) */
    ui_WIFI_AP_NAME_Label = lv_label_create(ui_WIFI_AP_Information);
    lv_obj_set_width(ui_WIFI_AP_NAME_Label, LV_SIZE_CONTENT);                                                    // Set width to content size
    lv_obj_set_height(ui_WIFI_AP_NAME_Label, LV_SIZE_CONTENT);                                                   // Set height to content size
    lv_obj_set_x(ui_WIFI_AP_NAME_Label, -130);                                                                   // Set x position relative to the parent container
    lv_obj_set_y(ui_WIFI_AP_NAME_Label, -120);                                                                   // Set y position relative to the parent container
    lv_obj_set_align(ui_WIFI_AP_NAME_Label, LV_ALIGN_CENTER);                                                    // Center align label
    lv_label_set_text(ui_WIFI_AP_NAME_Label, "SSID");                                                            // Set the text of the label to "SSID"
    lv_obj_set_style_text_color(ui_WIFI_AP_NAME_Label, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_AP_NAME_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully opaque
    lv_obj_set_style_text_font(ui_WIFI_AP_NAME_Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Create label for Password */
    ui_WIFI_AP_PWD_Label = lv_label_create(ui_WIFI_AP_Information);
    lv_obj_set_width(ui_WIFI_AP_PWD_Label, LV_SIZE_CONTENT);                                                    // Set width to content size
    lv_obj_set_height(ui_WIFI_AP_PWD_Label, LV_SIZE_CONTENT);                                                   // Set height to content size
    lv_obj_set_x(ui_WIFI_AP_PWD_Label, -161);                                                                   // Set x position relative to the parent container
    lv_obj_set_y(ui_WIFI_AP_PWD_Label, -70);                                                                    // Set y position relative to the parent container
    lv_obj_set_align(ui_WIFI_AP_PWD_Label, LV_ALIGN_CENTER);                                                    // Center align label
    lv_label_set_text(ui_WIFI_AP_PWD_Label, "Password");                                                        // Set the text of the label to "Password"
    lv_obj_set_style_text_color(ui_WIFI_AP_PWD_Label, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_AP_PWD_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully opaque
    lv_obj_set_style_text_font(ui_WIFI_AP_PWD_Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Create label for Wi-Fi Channel */
    ui_WIFI_AP_Channel_Label = lv_label_create(ui_WIFI_AP_Information);
    lv_obj_set_width(ui_WIFI_AP_Channel_Label, LV_SIZE_CONTENT);                                                    // Set width to content size
    lv_obj_set_height(ui_WIFI_AP_Channel_Label, LV_SIZE_CONTENT);                                                   // Set height to content size
    lv_obj_set_x(ui_WIFI_AP_Channel_Label, -152);                                                                   // Set x position relative to the parent container
    lv_obj_set_y(ui_WIFI_AP_Channel_Label, -20);                                                                    // Set y position relative to the parent container
    lv_obj_set_align(ui_WIFI_AP_Channel_Label, LV_ALIGN_CENTER);                                                    // Center align label
    lv_label_set_text(ui_WIFI_AP_Channel_Label, "Channel");                                                         // Set the text of the label to "Channel"
    lv_obj_set_style_text_color(ui_WIFI_AP_Channel_Label, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_AP_Channel_Label, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully opaque
    lv_obj_set_style_text_font(ui_WIFI_AP_Channel_Label, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Create container for MAC address information */
    ui_WIFI_AP_MAC_ADDR = lv_obj_create(ui_WIFI_OPEN_AP_);
    lv_obj_set_width(ui_WIFI_AP_MAC_ADDR, lv_pct(48));            // Set width to 48% of parent container
    lv_obj_set_height(ui_WIFI_AP_MAC_ADDR, lv_pct(84));           // Set height to 84% of parent container
    lv_obj_set_align(ui_WIFI_AP_MAC_ADDR, LV_ALIGN_BOTTOM_RIGHT); // Align container to the bottom right of the parent
    // lv_obj_add_flag(ui_WIFI_AP_MAC_ADDR, LV_OBJ_FLAG_HIDDEN);  // Optionally hide the container (disabled here)
    // Disable scrolling for the container
    lv_obj_clear_flag(ui_WIFI_AP_MAC_ADDR, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_WIFI_AP_MAC_ADDR, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);     // Set background color to white
    lv_obj_set_style_bg_opa(ui_WIFI_AP_MAC_ADDR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                            // Set background opacity to 0 (transparent)
    lv_obj_set_style_border_color(ui_WIFI_AP_MAC_ADDR, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set border color to black
    lv_obj_set_style_border_opa(ui_WIFI_AP_MAC_ADDR, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                        // Set border opacity to 0 (transparent)

    /* Create list inside MAC address container */
    ui_WIFI_AP_MAC_List = lv_list_create(ui_WIFI_AP_MAC_ADDR);
    lv_obj_set_width(ui_WIFI_AP_MAC_List, lv_pct(100));                                                        // Set list width to 100% of container
    lv_obj_set_height(ui_WIFI_AP_MAC_List, lv_pct(80));                                                        // Set list height to 80% of container
    lv_obj_set_x(ui_WIFI_AP_MAC_List, 10);                                                                     // Set x position of list within container
    lv_obj_set_align(ui_WIFI_AP_MAC_List, LV_ALIGN_BOTTOM_MID);                                                // Align list to the bottom center of the container
    lv_obj_set_scrollbar_mode(ui_WIFI_AP_MAC_List, LV_SCROLLBAR_MODE_OFF);                                     // Disable scrollbar for the list
    lv_obj_add_flag(ui_WIFI_AP_MAC_List, LV_OBJ_FLAG_HIDDEN);                                                  // Optionally hide the list (disabled here)
    lv_obj_set_style_bg_color(ui_WIFI_AP_MAC_List, lv_color_hex(0x001A40), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_WIFI_AP_MAC_List, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity to 0 (transparent)
    lv_obj_set_style_text_color(ui_WIFI_AP_MAC_List, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_AP_MAC_List, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully opaque

    /* Create label for connection status (whether AP is started or not) */
    ui_WIFI_AP_CON_NUM = lv_label_create(ui_WIFI_AP_MAC_ADDR);
    lv_obj_set_width(ui_WIFI_AP_CON_NUM, LV_SIZE_CONTENT);                                                    // Set width to content size
    lv_obj_set_height(ui_WIFI_AP_CON_NUM, LV_SIZE_CONTENT);                                                   // Set height to content size
    lv_obj_set_x(ui_WIFI_AP_CON_NUM, 10);                                                                     // Set x position within container
    lv_obj_set_y(ui_WIFI_AP_CON_NUM, -120);                                                                   // Set y position within container
    lv_obj_set_align(ui_WIFI_AP_CON_NUM, LV_ALIGN_LEFT_MID);                                                  // Align label to the left middle of the container
    lv_label_set_text(ui_WIFI_AP_CON_NUM, "AP is not started.");                                              // Set the label text
    lv_obj_set_style_text_color(ui_WIFI_AP_CON_NUM, lv_color_hex(0xFFA500), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to white
    lv_obj_set_style_text_opa(ui_WIFI_AP_CON_NUM, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully opaque
    lv_obj_set_style_text_font(ui_WIFI_AP_CON_NUM, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    /* Create a switch to enable or disable the Wi-Fi AP */
    ui_WIFI_AP_OPEN = lv_switch_create(ui_WIFI_OPEN_AP_);
    lv_obj_set_width(ui_WIFI_AP_OPEN, 50);                 // Set width of the switch to 50 pixels
    lv_obj_set_height(ui_WIFI_AP_OPEN, 30);                // Set height of the switch to 30 pixels
    lv_obj_set_x(ui_WIFI_AP_OPEN, 0);                      // Set x position of the switch
    lv_obj_set_y(ui_WIFI_AP_OPEN, 12);                     // Set y position of the switch
    lv_obj_set_align(ui_WIFI_AP_OPEN, LV_ALIGN_TOP_RIGHT); // Align the switch to the top right of the parent container

    /* Create a label to display input error message */
    ui_WIFI_AP_INPUT_ERROR = lv_label_create(ui_WIFI_OPEN_AP_);
    lv_obj_set_width(ui_WIFI_AP_INPUT_ERROR, LV_SIZE_CONTENT);                                                    // Set width to content size
    lv_obj_set_height(ui_WIFI_AP_INPUT_ERROR, LV_SIZE_CONTENT);                                                   // Set height to content size
    lv_obj_set_align(ui_WIFI_AP_INPUT_ERROR, LV_ALIGN_TOP_MID);                                                   // Center align the label horizontally
    lv_label_set_text(ui_WIFI_AP_INPUT_ERROR, "Please check if the box is empty.");                               // Set the error message text
    lv_obj_add_flag(ui_WIFI_AP_INPUT_ERROR, LV_OBJ_FLAG_HIDDEN);                                                  // Initially hide the error message
    lv_obj_set_style_text_color(ui_WIFI_AP_INPUT_ERROR, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT); // Set text color to red (error)
    lv_obj_set_style_text_opa(ui_WIFI_AP_INPUT_ERROR, 255, LV_PART_MAIN | LV_STATE_DEFAULT);                      // Set text opacity to fully opaque

    /* Create a keyboard for input */
    ui_WIFI_AP_Keyboard = lv_keyboard_create(ui_WIFI_AP);
    lv_obj_set_width(ui_WIFI_AP_Keyboard, lv_pct(100));                                                        // Set keyboard width to 100% of the parent container
    lv_obj_set_height(ui_WIFI_AP_Keyboard, lv_pct(50));                                                        // Set keyboard height to 50% of the parent container
    lv_obj_set_x(ui_WIFI_AP_Keyboard, 0);                                                                      // Set x position of the keyboard
    lv_obj_set_y(ui_WIFI_AP_Keyboard, 15);                                                                     // Set y position of the keyboard
    lv_obj_set_align(ui_WIFI_AP_Keyboard, LV_ALIGN_BOTTOM_MID);                                                // Align the keyboard to the bottom middle of the parent container
    lv_obj_add_flag(ui_WIFI_AP_Keyboard, LV_OBJ_FLAG_HIDDEN);                                                  // Initially hide the keyboard
    lv_obj_set_style_bg_color(ui_WIFI_AP_Keyboard, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);   // Set background color to white
    lv_obj_set_style_bg_opa(ui_WIFI_AP_Keyboard, 0, LV_PART_MAIN | LV_STATE_DEFAULT);                          // Set background opacity to 0 (transparent)
    lv_obj_set_style_text_font(ui_WIFI_AP_Keyboard, &lv_font_montserrat_14, LV_PART_ITEMS | LV_STATE_DEFAULT); // Set text font to Montserrat 14

    /* Add event callbacks for various buttons and input fields */
    lv_obj_add_event_cb(ui_WIFI_Button0, ui_event_WIFI_Button0, LV_EVENT_ALL, NULL);                     // Button0 event handler
    lv_obj_add_event_cb(ui_WIFI_OPEN, ui_event_WIFI_OPEN, LV_EVENT_ALL, NULL);                           // Wi-Fi Open switch event handler
    lv_obj_add_event_cb(ui_WIFI_Connection_BUTTON, ui_event_WIFI_Connection_BUTTON, LV_EVENT_ALL, NULL); // Connection button event handler
    lv_obj_add_event_cb(ui_WIFI_EYE, ui_event_WIFI_EYE, LV_EVENT_ALL, NULL);                             // Eye icon event handler for visibility toggle
    lv_obj_add_event_cb(ui_WIFI_INPUT_PWD, ui_event_WIFI_INPUT_PWD, LV_EVENT_ALL, NULL);                 // Password input field event handler
    lv_keyboard_set_textarea(ui_WIFI_INPUT_KEYBOARD, ui_WIFI_INPUT_PWD);                                 // Set the password input field as the keyboard's text area

    /* Additional event handlers for Wi-Fi AP settings */
    lv_obj_add_event_cb(ui_WIFI_Button2, ui_event_WIFI_Button2, LV_EVENT_ALL, NULL);         // Button2 event handler
    lv_obj_add_event_cb(ui_WIFI_AP_NAME, ui_event_WIFI_AP_NAME, LV_EVENT_ALL, NULL);         // AP Name input field event handler
    lv_obj_add_event_cb(ui_WIFI_AP_EYE, ui_event_WIFI_AP_EYE, LV_EVENT_ALL, NULL);           // Eye icon for AP Name event handler
    lv_obj_add_event_cb(ui_WIFI_AP_Password, ui_event_WIFI_AP_Password, LV_EVENT_ALL, NULL); // AP Password input field event handler
    lv_obj_add_event_cb(ui_WIFI_AP_Channel, ui_event_WIFI_AP_Channel, LV_EVENT_ALL, NULL);   // AP Channel input field event handler
    lv_obj_add_event_cb(ui_WIFI_AP_OPEN, ui_event_WIFI_AP_OPEN, LV_EVENT_ALL, NULL);         // AP Open switch event handler
    lv_keyboard_set_textarea(ui_WIFI_AP_Keyboard, ui_WIFI_AP_NAME);                          // Set the AP Name input field as the keyboard's text area
}
